# Trechos de matérias, highlights, casos famosos e discussões
# Inseridos ao longo da landing via render_section_highlights() e modais OWASP/CWE

COURSE_HIGHLIGHTS = [
  # ── Introdução ──
  {"id": "intro-quote-owasp", "type": "quote", "sections": ["intro"],
   "source": "OWASP Top 10:2025 — Introdução",
   "title": "Data-informed, não opinião isolada",
   "excerpt": "«The OWASP Top 10 is a standard awareness document for developers and web application security. It represents a broad consensus about the most critical security risks to web applications.» A edição 2025 combina 2,8M+ aplicações testadas com pesquisa comunitária para categorias sub-representadas em scanners.",
   "takeaway": "O ranking reflete o que ferramentas e pentesters encontram — não substitui threat model do seu domínio.",
   "link": "https://owasp.org/Top10/2025/0x00_2025-Introduction/"},
  {"id": "intro-highlight-cve", "type": "highlight", "sections": ["intro"],
   "source": "MITRE CWE TOP 25 2025",
   "title": "67% das CVEs agora têm CWE mapeado pelo CNA",
   "excerpt": "O salto de +14 pontos percentuais em mapeamento CNA melhora a qualidade do ranking: menos abstrações genéricas, mais fraquezas Base/Variant acionáveis em revisão de código e triagem de patch.",
   "takeaway": "Priorize correção onde CVE, CWE e categoria OWASP convergem — é onde o ecossistema já concorda na root cause.",
   "link": "https://cwe.mitre.org/top25/archive/2025/2025_key_insights.html"},

  # ── Mercado ──
  {"id": "mercado-caso-snowflake", "type": "caso", "sections": ["mercado"],
   "owasp": "A02", "cwe": "CWE-306",
   "source": "CISA Advisory · Snowflake 2024",
   "title": "Snowflake — centenas de tenants sem MFA",
   "excerpt": "Campanha UNC5537 explorou contas Snowflake com autenticação fraca e credenciais reutilizadas. Ticketmaster, Santander e dezenas de outros clientes tiveram dados exfiltrados.",
   "detail": "Não houve zero-day — o atacante usou credenciais vazadas em ambientes onde MFA não era obrigatório por padrão. Session hijack e data exfiltration em escala industrial.",
   "stats": [("165+", "Clientes"), ("A02+A07", "Categorias"), ("2024", "Campanha")],
   "bullets": ["MFA obrigatório em todo tenant SaaS", "Rotacionar credenciais após vazamento", "Monitorar login anômalo via CTI"],
   "takeaway": "Misconfiguration (A02) + auth fraca (A07) compõem o vetor mais barato para atacantes em SaaS multi-tenant.",
   "link": "https://www.cisa.gov/news-events/cybersecurity-advisories"},
  {"id": "mercado-aprendizado-custo", "type": "aprendizado", "sections": ["mercado"],
   "source": "IBM Cost of a Data Breach 2024",
   "title": "Automação de IR reduz US$ 1,76M no custo médio",
   "excerpt": "Organizações com security AI e automação encurtaram o ciclo de vida do incidente em 108 dias. O gap não é só ferramenta — é detectar, correlacionar e responder antes que logging vire arquivo morto (A09).",
   "takeaway": "ROI de AppSec inclui MTTI/MTTR: investir em alerting acionável paga mais que comprar mais um scanner.",
   "link": "https://www.ibm.com/reports/data-breach"},
  {"id": "mercado-excerpt-dbir", "type": "excerpt", "sections": ["mercado"],
   "source": "Verizon DBIR 2024",
   "title": "Credenciais ainda dominam o vetor inicial",
   "excerpt": "Uso de credenciais roubadas e credential stuffing permanecem entre os principais vetores de breach em aplicações web. Misconfiguration responde por parcela significativa dos ataques web — alinhado com A02 subindo para #2 no OWASP 2025.",
   "takeaway": "MFA, rate limit e monitoramento de credenciais vazadas são controles de mercado, não diferencial opcional.",
   "link": "https://www.verizon.com/business/resources/reports/dbir/"},

  # ── Pesquisa / Intel ──
  {"id": "pesquisa-highlight-kev", "type": "highlight", "sections": ["pesquisa"],
   "source": "CISA KEV Catalog",
   "title": "Patch KEV antes de hardening genérico",
   "excerpt": "O catálogo Known Exploited Vulnerabilities lista CVEs com exploit confirmado in-the-wild. CWE-78 (OS Command Injection) lidera em entradas — relevante mesmo em apps web com bindings nativos, parsers PDF e pipelines CI.",
   "takeaway": "SLA de patch < 48h para KEV; WAF temporário só enquanto o patch não desce para produção.",
   "link": "https://www.cisa.gov/known-exploited-vulnerabilities-catalog"},
  {"id": "pesquisa-pos-threat-intel", "type": "pos", "sections": ["pesquisa"],
   "source": "Guia · Inteligência de ameaças",
   "title": "De relatório a backlog de engenharia",
   "excerpt": "Para cada insight do hub (MITRE, OWASP, DBIR, IBM), pergunte: qual user story quebra se isso for explorado? Qual teste automatizado detecta? Quem é owner do controle? Sem essa ponte, intel vira slide — não sprint.",
   "takeaway": "Exercício: escolha 1 CWE do TOP 25 e derive 2 user stories de abuso + 1 gate de CI.",
   "link": None},

  # ── Correlação ──
  {"id": "corr-aprendizado-mapa", "type": "aprendizado", "sections": ["correlacao"],
   "source": "OWASP ↔ CWE Mapping",
   "title": "Uma CWE, várias categorias OWASP",
   "excerpt": "CWE-200 (Exposure) aparece em A02 (misconfig) e A09 (logs). CWE-502 liga A03 (supply chain) e A08 (integridade). A matriz 10×25 mostra onde priorizar esforço quando o mesmo defeito alimenta múltiplos riscos de compliance.",
   "takeaway": "Clique na célula da matriz para filtrar toda a página — use como índice vivo durante o estudo.",
   "link": "https://cwe.mitre.org/documents/cwe_usage/guidance.html"},
  {"id": "corr-caso-moveit", "type": "caso", "sections": ["owasp-modal"],
   "owasp": "A05", "cwe": "CWE-89",
   "source": "CVE-2023-34362 · MOVEit",
   "title": "MOVEit — SQLi zero-day em produto legado",
   "excerpt": "Cl0p explorou SQL injection em Progress MOVEit Transfer. Mais de 2.500 organizações afetadas — BBC, British Airways, Maximus. Patch tardio + superfície exposta na internet = breach em escala industrial.",
   "takeaway": "Injection (A05) em software de transferência crítico mostra que 'não é nossa stack' não é defesa.",
   "link": "https://nvd.nist.gov/vuln/detail/CVE-2023-34362"},

  # ── Terminal Lab ──
  {"id": "term-highlight-cli", "type": "highlight", "sections": ["terminal-lab"],
   "owasp": "A01", "cwe": "CWE-639",
   "source": "OWASP WSTG",
   "title": "CLI reproduz o que o relatório descreve",
   "excerpt": "curl, sqlmap e jwt_tool no terminal didático espelham passos do Web Security Testing Guide. A diferença entre ler sobre IDOR e ver o JSON de outro usuário no terminal é o que fixa o conceito para auditoria e dev.",
   "detail": [
     "Cada lab do terminal mapeia para um capítulo WSTG: WSTG-ATHZ-03 (IDOR), WSTG-INPV-05 (SQLi), WSTG-SESS-10 (JWT). A saída formatada simula o que você colaria em um laudo de pentest.",
     "O fluxo didático segue a mesma ordem da IDE Juice Shop: reproduzir → entender → corrigir → validar que o exploit falha.",
   ],
   "stats": [("12+", "Comandos"), ("WSTG", "Guia base"), ("A01–A07", "OWASP cobertos")],
   "bullets": [
     "curl /rest/basket/{id} — IDOR sem checagem de ownership (CWE-639)",
     "sqlmap no login — valida CWE-89 com payload real do Juice Shop",
     "jwt decode + alg:none — testa A07/A08 em lib/insecurity.ts",
     "npm audit — correlaciona A03 com CVEs intencionais do package.json",
   ],
   "takeaway": "Digite help no terminal, execute o exploit, depois fix — mesma ordem da IDE Juice Shop.",
   "link": "https://owasp.org/www-project-web-security-testing-guide/"},
  {"id": "term-pos-evidencia", "type": "pos", "sections": ["terminal-lab"],
   "owasp": "A09", "cwe": "CWE-200",
   "source": "Prática · Evidências",
   "title": "Captura de evidência para laudo",
   "excerpt": "Em pentest ou auditoria, cada comando bem-sucedido deve gerar: request/response redigido, timestamp, impacto (confidencialidade/integridade/disponibilidade) e CWE/OWASP mapeados. O terminal desta página simula a cadeia de reprodução.",
   "detail": [
     "Um achado completo inclui: descrição técnica, passos de reprodução, evidência (screenshot ou log redigido), classificação CVSS simplificada e recomendação de mitigação com referência ASVS.",
     "Em laboratório, trate cada sessão no terminal como mini-relatório: hipótese → teste → resultado → conclusão.",
   ],
   "stats": [("CIA", "Triade impacto"), ("Art. 46", "LGPD"), ("ASVS", "Controle ref.")],
   "bullets": [
     "Redija e-mails, tokens e CPF antes de colar output — minimização de PII",
     "Registre HTTP method, path, status code e trecho relevante do body",
     "Mapeie cada achado a OWASP + CWE + severidade para o backlog",
     "Inclua comando fix ou snippet de correção na recomendação",
   ],
   "why": "Relatórios sem evidência reproduzível não sobrevivem a reteste nem a auditoria ANPD/GDPR.",
   "takeaway": "Pratique redigir PII antes de colar output em relatório — LGPD Art. 46 exige minimização.",
   "link": "https://www.gov.br/anpd/pt-br"},

  # ── Cofre de código ──
  {"id": "vault-aprendizado-diff", "type": "aprendizado", "sections": ["code-vault"],
   "source": "Cofre de Código",
   "title": "Diff vulnerável → correção é o artefato central",
   "excerpt": "Cada padrão no cofre mostra o anti-pattern exato e a correção idiomática na linguagem do exemplo. Em code review, treine o olho para o mesmo shape: concatenação em query, substring em redirect, parse sem validação.",
   "takeaway": "Abra o padrão, copie o checklist ASVS da categoria OWASP correspondente e marque item a item.",
   "link": None},
  {"id": "vault-quote-juice", "type": "quote", "sections": ["code-vault", "juice-ide"],
   "source": "OWASP Juice Shop",
   "title": "Vulnerabilidades intencionais com código de produção real",
   "excerpt": "«Juice Shop is an intentionally insecure web application for security trainings written in Node.js, Express and Angular.» Os trechos em routes/ e lib/ são os mesmos padrões encontrados em auditorias reais — apenas concentrados em um repositório didático.",
   "takeaway": "grep no clone local correlaciona achado de scanner com linha de código — prática recomendada antes do quiz.",
   "link": "https://github.com/juice-shop/juice-shop"},

  # ── Simuladores ──
  {"id": "sim-cwe-highlight", "type": "highlight", "sections": ["simuladores-cwe"],
   "source": "MITRE CWE TOP 25",
   "title": "CWE como lente sobre o mesmo código",
   "excerpt": "O mesmo login.ts do Juice Shop é CWE-89 (SQLi) e categoria A05 (Injection). Os 25 simuladores CWE forçam vocabulário MITRE — essencial para triagem de CVE, relatórios SOC e comunicação com desenvolvimento.",
   "takeaway": "Memorize o TOP 10 CWE por score; o restante consulte pela matriz de correlação.",
   "link": "https://cwe.mitre.org/top25/"},

  # ── OWASP modais (por categoria) ──
  {"id": "a01-quote-portswigger", "type": "quote", "sections": ["owasp-modal"],
   "owasp": "A01",
   "source": "PortSwigger Research 2024",
   "title": "IDOR em 94% dos aplicativos testados",
   "excerpt": "Broken Access Control não é exagero de consultoria — é a falha mais encontrada em pentest manual. APIs REST com IDs sequenciais e GraphQL sem authZ por field continuam entregando dados de terceiros.",
   "takeaway": "Teste horizontal (trocar ID) e vertical (/admin) em toda rota autenticada — não só no login.",
   "link": "https://portswigger.net/research"},
  {"id": "a01-caso-capitalone", "type": "caso", "sections": ["owasp-modal"],
   "owasp": "A01", "cwe": "CWE-918",
   "source": "DOJ · Capital One 2019",
   "title": "Capital One — SSRF para metadata AWS",
   "excerpt": "Ex-funcionária explorou SSRF em WAF para acessar 169.254.169.254 e obter credenciais IAM. 106 milhões de registros exfiltrados. A lição: qualquer fetch de URL user-controlled em cloud é candidato a A01.",
   "takeaway": "Bloqueie metadata IPs, use IMDSv2 e negue por padrão em outbound da aplicação.",
   "link": "https://www.justice.gov/usao-wdwa/pr/former-amazon-employee-convicted-hacking-capital-one-and-other-companies"},
  {"id": "a01-pos-bola", "type": "pos", "sections": ["owasp-modal"],
   "owasp": "A01",
   "source": "OWASP API Security Top 10",
   "title": "BOLA é o novo nome do IDOR em APIs",
   "excerpt": "API1:2023 Broken Object Level Authorization descreve o mesmo defeito de basket.ts — confiar no ID do recurso sem checar ownership no servidor. Em microsserviços, o bug migra para service-to-service tokens mal escopados.",
   "takeaway": "Desenhe authZ no diagrama de sequência antes do OpenAPI spec.",
   "link": "https://owasp.org/API-Security/"},

  {"id": "a02-caso-powerapps", "type": "caso", "sections": ["owasp-modal"],
   "owasp": "A02", "cwe": "CWE-200",
   "source": "UpGuard · Microsoft Power Apps 2021",
   "title": "Power Apps — 38M registros públicos por default",
   "excerpt": "Listas configuradas como públicas expuseram PII, dados de COVID e informações corporativas. Não houve exploit sofisticado — apenas default inseguro não revisado em escala.",
   "takeaway": "Inventário de assets + scan contínuo de permissões públicas em SaaS e cloud storage.",
   "link": "https://www.upguard.com/"},
  {"id": "a02-aprendizado-cis", "type": "aprendizado", "sections": ["owasp-modal"],
   "owasp": "A02",
   "source": "CIS Benchmarks",
   "title": "Misconfig é corrigida por policy-as-code",
   "excerpt": "Diferente de bug lógico, configuração insegura responde a baseline automatizado: Terraform plan com OPA, AWS Config, K8s admission controllers. O DBIR atribui ~15% dos ataques web a misconfiguration.",
   "takeaway": "Todo PR de infra deve falhar se bucket público ou security group 0.0.0.0/0.",
   "link": "https://www.cisecurity.org/cis-benchmarks"},

  {"id": "a03-caso-solarwinds", "type": "caso", "sections": ["owasp-modal"],
   "owasp": "A03", "cwe": "CWE-829",
   "source": "CISA · SolarWinds 2020",
   "title": "SUNBURST — update assinado com backdoor",
   "excerpt": "Código malicioso inserido no pipeline de build do Orion. 18.000+ organizações instalaram o update confiando na assinatura digital. Supply chain destrói a premissa 'confie no vendor'.",
   "takeaway": "SBOM + proveniência SLSA + monitoramento de comportamento em runtime — assinatura sozinha não basta.",
   "link": "https://www.cisa.gov/news-events/cybersecurity-advisories/aa20-352a"},
  {"id": "a03-caso-xz", "type": "caso", "sections": ["owasp-modal"],
   "owasp": "A03", "cwe": "CWE-829",
   "source": "CVE-2024-3094 · XZ Utils",
   "title": "XZ Utils — social engineering no maintainer",
   "excerpt": "Backdoor em liblzma após anos de pressão sobre maintainer solo. Detectado por anomalia em sshd, não por scanner de dependências. Ameaça a open source sob-financiado entrou no TOP 25 via A03:2025.",
   "takeaway": "Pin de versão, hash verification e revisão humana de mudanças críticas em dependências nativas.",
   "link": "https://nvd.nist.gov/vuln/detail/CVE-2024-3094"},

  {"id": "a04-highlight-md5", "type": "highlight", "sections": ["owasp-modal"],
   "owasp": "A04", "cwe": "CWE-327",
   "source": "OWASP ASVS 4.0",
   "title": "MD5 e SHA-1 para senha violam ASVS 2.4.1",
   "excerpt": "Juice Shop usa MD5 em lib/insecurity.ts de propósito. Em produção, bcrypt/Argon2id com salt único e pepper em vault são baseline. Criptografia errada não precisa de atacante ativo — basta vazamento offline.",
   "takeaway": "Audite hash de senha e algoritmo de JWT no primeiro dia de onboarding em código legado.",
   "link": "https://owasp.org/www-project-application-security-verification-standard/"},

  {"id": "a05-caso-equifax", "type": "caso", "sections": ["owasp-modal"],
   "owasp": "A05", "cwe": "CWE-94",
   "source": "Equifax · CVE-2017-5638",
   "title": "Equifax — patch não aplicado por 2 meses",
   "excerpt": "Apache Struts OGNL injection (CVE-2017-5638) conhecida e patcheável. 147 milhões de registros. Injection aqui é falha de processo (vuln management) tanto quanto de código.",
   "takeaway": "SLA de patch proporcional ao CVSS + exposição; Struts na internet é prioridade zero.",
   "link": "https://nvd.nist.gov/vuln/detail/CVE-2017-5638"},
  {"id": "a05-quote-owasp", "type": "quote", "sections": ["owasp-modal"],
   "owasp": "A05",
   "source": "OWASP A05:2025",
   "title": "Injection caiu de #3 para #5 — mas XSS lidera o CWE",
   "excerpt": "A categoria Injection permanece crítica: mais CVEs associadas que qualquer outra. XSS (CWE-79) tem frequência altíssima; SQLi mantém impacto desproporcional em dados estruturados.",
   "takeaway": "Parameterized queries + context-aware encoding — duas trilhas paralelas, não OU.",
   "link": "https://owasp.org/Top10/2025/A05_2025-Injection/"},

  {"id": "a06-pos-design", "type": "pos", "sections": ["owasp-modal"],
   "owasp": "A06",
   "source": "NIST SSDF · PW.1",
   "title": "Threat model antes do sprint 1",
   "excerpt": "Insecure Design (A06) captura falhas que nenhum WAF corrige: preço negativo, cupom reutilizável, race em estoque, CSRF em ação irreversível. O custo de redesenhar após produção é ordens de magnitude maior.",
   "takeaway": "Abuse cases no backlog junto com user stories — mesma prioridade de negócio.",
   "link": "https://csrc.nist.gov/Projects/ssdf"},

  {"id": "a07-caso-okta", "type": "caso", "sections": ["owasp-modal"],
   "owasp": "A07", "cwe": "CWE-200",
   "source": "Okta Security 2022",
   "title": "Okta Support — sessões de clientes expostas",
   "excerpt": "Comprometimento do sistema de suporte permitiu acesso a sessões de clientes enterprise. Quem guarda identidade centralizada concentra risco — MFA, least privilege e segregação de ambientes de suporte são mandatórios.",
   "takeaway": "IdP e helpdesk são tier-0 — mesmo rigor de produção, auditoria contínua.",
   "link": "https://sec.okta.com/"},

  {"id": "a08-caso-codecov", "type": "caso", "sections": ["owasp-modal"],
   "owasp": "A08", "cwe": "CWE-345",
   "source": "Codecov 2021",
   "title": "Codecov — script CI modificado por meses",
   "excerpt": "Atacante alterou bash uploader para exfiltrar secrets de CI. 29.000+ ambientes afetados. Integridade de artefatos de build (A08) é extensão direta de supply chain (A03).",
   "takeaway": "Assine artefatos de CI, pin scripts por hash, rotacione secrets após suspeita.",
   "link": "https://about.codecov.io/security-update"},

  {"id": "a09-aprendizado-lgpd", "type": "aprendizado", "sections": ["owasp-modal"],
   "owasp": "A09",
   "source": "LGPD Art. 46 · GDPR Art. 32",
   "title": "Log sem alerta é gap legal e técnico",
   "excerpt": "ANPD e reguladores europeus esperam capacidade de detectar incidentes — não apenas armazenar logs. A09:2025 renomeia a categoria para enfatizar alerting, não archiving.",
   "takeaway": "Defina 3 alertas acionáveis antes de aumentar retenção de log.",
   "link": "https://www.gov.br/anpd/pt-br"},

  {"id": "a10-caso-heartbleed", "type": "caso", "sections": ["owasp-modal"],
   "owasp": "A10", "cwe": "CWE-125",
   "source": "Heartbleed · CVE-2014-0160",
   "title": "Heartbleed — exceção mal tratada vazou memória",
   "excerpt": "OpenSSL TLS heartbeat permitiu leitura out-of-bounds de 64KB por request — chaves privadas, sessões, credenciais. A10 cobre error handling, fail-open e estados inconsistentes após exceção.",
   "takeaway": "Fail-closed em authZ; nunca retornar stack trace ao cliente; fuzz em parsers nativos.",
   "link": "https://nvd.nist.gov/vuln/detail/CVE-2014-0160"},

  # ── CWE modais (TOP 10 por ranking) ──
  {"id": "cwe79-highlight", "type": "highlight", "sections": ["cwe-modal"],
   "cwe": "CWE-79", "owasp": "A05",
   "source": "MITRE CWE TOP 25 2025",
   "title": "CWE-79 lidera com score 60,38",
   "excerpt": "Cross-site Scripting permanece #1 apesar de +3.000 CVEs novas no dataset. Stored XSS em painéis admin e DOM XSS em SPAs continuam entregando takeover de sessão.",
   "takeaway": "CSP com nonce + encode na saída conforme contexto HTML/JS/URL.",
   "link": "https://cwe.mitre.org/data/definitions/79.html"},
  {"id": "cwe89-caso", "type": "caso", "sections": ["cwe-modal"],
   "cwe": "CWE-89", "owasp": "A05",
   "source": "OWASP Testing Guide · SQLi",
   "title": "SQLi — de login bypass a RCE em DBMS",
   "excerpt": "Concatenação em login.ts é o padrão clássico. UNION em search.ts demonstra exfiltração. Em MySQL com FILE privilege, SQLi escala para leitura de arquivos — CWE-89 raramente fica só em leitura de tabela.",
   "takeaway": "ORM/prepared statements em 100% dos queries; deny-list de funções perigosas no DB user.",
   "link": "https://owasp.org/www-community/attacks/SQL_Injection"},
  {"id": "cwe862-highlight", "type": "highlight", "sections": ["cwe-modal"],
   "cwe": "CWE-862", "owasp": "A01",
   "source": "MITRE CWE TOP 25 2025",
   "title": "CWE-862 subiu 5 posições — #4 no ranking",
   "excerpt": "Missing Authorization reflete APIs que autenticam mas não autorizam por recurso. Correlação direta com A01 e com achados PortSwigger/DBIR em IDOR e BOLA.",
   "takeaway": "Middleware de authZ por rota + teste automatizado trocando JWT entre usuários.",
   "link": "https://cwe.mitre.org/data/definitions/862.html"},
  {"id": "cwe918-caso", "type": "caso", "sections": ["cwe-modal"],
   "cwe": "CWE-918", "owasp": "A01",
   "source": "Capital One · SSRF",
   "title": "SSRF — da URL fetch ao metadata cloud",
   "excerpt": "CWE-918 caiu para #22 no TOP 25 mas permanece crítico em Kubernetes e serverless. Qualquer proxy de imagem, webhook ou import URL é superfície.",
   "takeaway": "Allowlist de destinos, bloqueio de RFC1918 e metadata, timeout agressivo.",
   "link": "https://cwe.mitre.org/data/definitions/918.html"},
  {"id": "cwe502-highlight", "type": "highlight", "sections": ["cwe-modal"],
   "cwe": "CWE-502", "owasp": "A08",
   "source": "CISA KEV",
   "title": "Deserialização — 11 CVEs no KEV",
   "excerpt": "Java, .NET e Node mantêm gadget chains ativas. Juice Shop yaml.load em vm é caricatura do mesmo anti-pattern em parsers de upload.",
   "takeaway": "Nunca deserializar input não confiável; JSON schema + rejeição de tipos perigosos.",
   "link": "https://cwe.mitre.org/data/definitions/502.html"},

  # ── Hubs (visão geral) ──
  {"id": "cwe-hub-aprendizado", "type": "aprendizado", "sections": ["cwe-hub"],
   "source": "MITRE CWE",
   "title": "Score MITRE ≠ frequência no seu código",
   "excerpt": "O ranking agrega CVEs globais. Sua aplicação pode ter CWE-352 (CSRF) frequente e CWE-787 rara. Use o score para priorizar estudo; use o repositório para priorizar sprint.",
   "takeaway": "Cruze SAST local com TOP 25 — interseção define o backlog do trimestre.",
   "link": "https://cwe.mitre.org/top25/"},

  # ── Juice / Checkpoint ──
  {"id": "juice-pos", "type": "pos", "sections": ["juice-ide"],
   "source": "Lab prático",
   "title": "Da vulnerabilidade ao patch verificável",
   "excerpt": "Fluxo completo: reproduzir no terminal → entender root cause na IDE → aplicar correção digitada → validar que o exploit falha. Documente CWE, OWASP, arquivo e linha no relatório — mesmo formato de ticket Jira em time maduro.",
   "takeaway": "Mínimo 3 labs documentados com evidência antes/depois.",
   "link": None},
  {"id": "quiz-aprendizado", "type": "aprendizado", "sections": ["quiz"],
   "source": "Quiz",
   "title": "Quiz testa correlação, não memorização de ranking",
   "excerpt": "Perguntas cruzam OWASP 2025 vs 2021, CWE em KEV e mapeamento Juice Shop. Errou? Volte ao modal da categoria, aba Casos ou Destaques, e refaça o lab correspondente.",
   "takeaway": "Meta: 80%+ acertos antes de considerar o conteúdo assimilado.",
   "link": None},
  {"id": "quiz-quote", "type": "quote", "sections": ["quiz"],
   "source": "Quiz · Estudo de caso",
   "title": "«O que não é medido, não é aprendido»",
   "excerpt": "O quiz não testa memorização — verifica se você consegue correlacionar OWASP, CWE, evidência de exploit e mitigação. Cada erro aponta para um lab específico nesta página.",
   "takeaway": "Refaça o lab indicado antes de avançar — repetição com evidência fixa o conceito.",
   "link": None},

  # ── Notícias (contexto editorial) ──
  {"id": "news-quote-mitre", "type": "quote", "sections": ["noticias"],
   "source": "MITRE Corporation · CWE TOP 25",
   "title": "Root cause mapping é o objetivo do CWE",
   "excerpt": "«The CWE Top 25 is a compilation of the most common and impactful weakness types in software. The goal is to help prioritize mitigation efforts by focusing on weaknesses that are most often exploited.» O ranking 2025 prioriza mapeamentos CNA reais — não normalização forçada do NVD.",
   "takeaway": "Use o TOP 25 para priorizar estudo; use CNA mapping no seu programa de disclosure interno.",
   "link": "https://cwe.mitre.org/top25/"},
  {"id": "news-mencao-schneier", "type": "mencao", "sections": ["noticias"],
   "author": "Bruce Schneier · Schneier on Security",
   "source": "Menção · Security mindset",
   "title": "Segurança é um processo, não um produto",
   "excerpt": "Schneier repete há décadas: comprar ferramenta sem processo de patch, revisão e resposta não fecha risco. Os relatórios desta seção (DBIR, IBM, MITRE) quantificam o que ele descreve qualitativamente — breaches continuam por falhas conhecidas e não corrigidas.",
   "detail": "Cada notícia abaixo deve virar uma ação verificável — não apenas clipping.",
   "bullets": ["Relacione headline → OWASP → CWE → controle", "Pergunte: isso existe no nosso stack?", "Derive 1 ticket de engenharia por incidente lido"],
   "takeaway": "Curadoria sem backlog é leitura passiva — exigimos ação rastreável.",
   "link": "https://www.schneier.com/"},
  {"id": "news-excerpt-dbir25", "type": "excerpt", "sections": ["noticias"],
   "owasp": "A03", "cwe": "CWE-829",
   "source": "Verizon DBIR 2025",
   "title": "Terceiros dobraram — supply chain é vetor, não buzzword",
   "excerpt": "O DBIR 2025 reporta que ameaças via terceiros praticamente dobraram. Intrusão em sistemas aparece em 81% dos casos. A curadoria de notícias abaixo inclui incidentes que começaram em vendor, update ou credencial de parceiro.",
   "stats": [("2×", "Terceiros"), ("81%", "Intrusão"), ("A03", "OWASP")],
   "takeaway": "Ao ler cada card de notícia, identifique se o vetor foi interno, terceiro ou supply chain.",
   "link": "https://www.verizon.com/business/resources/reports/dbir/"},

  # ── Juice setup ──
  {"id": "juice-setup-quote", "type": "quote", "sections": ["juice-setup"],
   "source": "OWASP Juice Shop · README",
   "title": "«Know it. Exploit it. Fix it.»",
   "excerpt": "«OWASP Juice Shop is probably the most modern and sophisticated insecure web application! It can be used in security trainings, awareness demos, CTFs and as a guinea pig for security tools!» O setup abaixo sobe o ambiente em menos de 2 minutos — o trabalho começa no código-fonte.",
   "bullets": ["Docker: porta 3000 · Score Board em /#/score-board", "Clone local: npm audit para A03", "grep routes/ para achar SQLi e IDOR"],
   "takeaway": "Suba o lab antes de abrir a IDE — validação no terminal usa localhost:3000.",
   "link": "https://github.com/juice-shop/juice-shop"},
  {"id": "juice-setup-mencao-kim", "type": "mencao", "sections": ["juice-setup"],
   "author": "Troy Hunt · Have I Been Pwned",
   "source": "Menção · Treino prático",
   "title": "Aprender segurança exige quebrar coisas em ambiente controlado",
   "excerpt": "Hunt defende labs intencionalmente vulneráveis como ponte entre teoria e reflexo profissional — o mesmo princípio do Juice Shop citado em treinamentos OWASP globais. Você não aprende IDOR lendo só a definição CWE-639.",
   "detail": "Após o docker compose, rode o Score Board e tente 3 challenges mapeados neste guia antes de seguir para a IDE.",
   "takeaway": "Challenge resolvido = 1 evidência para o relatório técnico.",
   "link": "https://www.troyhunt.com/"},

  # ── Mais intro / mercado / pesquisa ──
  {"id": "intro-mencao-saltzer", "type": "mencao", "sections": ["intro"],
   "author": "Jerome Saltzer & Murray Schroeder · MIT, 1975",
   "source": "Menção · Design clássico",
   "title": "Princípio da menor privilégio — 50 anos depois ainda violado",
   "excerpt": "O artigo original de proteção em sistemas de informação estabeleceu least privilege e fail-safe defaults. A01 (Broken Access Control) e A02 (Misconfig) são, em essência, violações sistêmicas desses princípios — não bugs de sintaxe.",
   "takeaway": "Cada categoria OWASP neste guia mapeia para um princípio de design que já existia antes da web.",
   "link": "https://csrc.nist.gov/publications/detail/sp/800-12/rev-1/final"},
  {"id": "mercado-quote-ibm", "type": "quote", "sections": ["mercado"],
   "source": "IBM Security · Cost of a Data Breach 2025",
   "title": "IA sem governança aumenta custo e frequência",
   "excerpt": "«Organizations with extensive use of security AI and automation reported significantly lower breach costs and faster incident resolution.» O inverso também aparece nos dados: 97% tiveram incidentes de IA sem controles adequados — novo eixo de risco além do Top 10 clássico.",
   "stats": [("US$ 4,4M", "Custo médio"), ("97%", "IA sem controles")],
   "takeaway": "Ao discutir ROI de AppSec, inclua MTTR — não só prevenção de vuln.",
   "link": "https://www.ibm.com/reports/data-breach"},
  {"id": "pesquisa-quote-cisa", "type": "quote", "sections": ["pesquisa"],
   "owasp": "A02", "cwe": "CWE-78",
   "source": "CISA · Binding Operational Directive",
   "title": "KEV não é opcional para órgãos US — referência global de prioridade",
   "excerpt": "«Federal Civilian Executive Branch agencies are required to remediate vulnerabilities identified in the CISA KEV catalog within prescribed timeframes.» Mesmo fora do setor público US, o KEV é o melhor proxy de «explorado agora» disponível gratuitamente.",
   "bullets": ["Patch KEV em < 48h", "Inventário semanal do catálogo", "WAF rule só como mitigação temporária"],
   "takeaway": "Cruze KEV com seu SBOM — interseção é sprint zero.",
   "link": "https://www.cisa.gov/known-exploited-vulnerabilities-catalog"},
  {"id": "pesquisa-mencao-shostack", "type": "mencao", "sections": ["pesquisa", "owasp-modal"],
   "owasp": "A06",
   "author": "Adam Shostack · Threat Modeling",
   "source": "Menção · Threat modeling",
   "title": "«Threat modeling is a family of activities»",
   "excerpt": "Shostack enfatiza que threat model não é diagrama bonito — é atividade repetida que alimenta design seguro (A06). STRIDE, attack trees e misuse cases devem aparecer no backlog, não só no Confluence.",
   "takeaway": "Para cada categoria OWASP, pergunte no threat model: como isso seria abusado?",
   "link": "https://www.threatmodelingbook.com/"},

  # ── Correlação / simuladores extras ──
  {"id": "corr-quote-owasp-cwe", "type": "quote", "sections": ["correlacao"],
   "source": "OWASP Foundation",
   "title": "OWASP e MITRE CWE são complementares",
   "excerpt": "«OWASP Top 10 categories are mapped to CWEs to provide a deeper technical understanding of the weaknesses that can lead to each risk category.» A matriz interativa torna esse mapeamento navegável — clique filtra toda a página.",
   "takeaway": "OWASP responde «o que priorizar»; CWE responde «qual defeito no código».",
   "link": "https://owasp.org/Top10/2025/"},
  {"id": "sim-quote-kohn", "type": "quote", "sections": ["simuladores"],
   "source": "Aprendizado ativo",
   "title": "«Tell me and I forget. Teach me and I remember. Involve me and I learn.»",
   "excerpt": "Atribuída a Benjamin Franklin — resume a abordagem dos simuladores: executar o ataque, ver o impacto, aplicar o fix. Passivo não fixa padrão de código inseguro no olho do desenvolvedor.",
   "takeaway": "Cada simulador deve terminar com Fix aplicado — não só exploit.",
   "link": None},
  {"id": "sim-cwe-mencao-hoglund", "type": "mencao", "sections": ["simuladores-cwe"],
   "author": "Greg Hoglund & Gary McGraw · Exploiting Software",
   "source": "Menção · Root cause",
   "title": "Atacantes pensam em inputs que devs não imaginam",
   "excerpt": "O livro clássico separa bugs de flaws — design flaws (A06) vs implementation bugs (A05/A01). Os 25 simuladores CWE focam implementation; combine com abuse cases para cobrir design.",
   "takeaway": "Se o simulador CWE passou mas o abuse case falhou, o risco ainda existe.",
   "link": None},

  # ── OWASP modais — complementos faltantes ──
  {"id": "a02-quote-dbir", "type": "quote", "sections": ["owasp-modal"],
   "owasp": "A02",
   "source": "Verizon DBIR 2024",
   "title": "«Misconfiguration is not a small problem»",
   "excerpt": "Cerca de 15% dos ataques web analisados no DBIR envolvem misconfiguration — buckets públicos, permissões excessivas, headers ausentes. A02 subiu para #2 no OWASP 2025 porque cloud e SaaS multiplicaram superfície configurável.",
   "takeaway": "IaC review é tão importante quanto code review.",
   "link": "https://www.verizon.com/business/resources/reports/dbir/"},
  {"id": "a03-mencao-slsa", "type": "mencao", "sections": ["owasp-modal"],
   "owasp": "A03",
   "author": "OpenSSF · SLSA framework",
   "source": "Menção · Supply chain",
   "title": "Proveniência assinada — do build ao deploy",
   "excerpt": "SLSA (Supply-chain Levels for Software Artifacts) define níveis de maturidade: script build, build service, hermético, dois pontos de revisão. SolarWinds e XZ Utils falharam em múltiplos níveis — não só «dependência velha».",
   "bullets": ["SBOM em todo release", "Assinatura de artefato", "Política de dependência pinada"],
   "takeaway": "A03:2025 é categoria de processo — npm audit sozinho não cobre.",
   "link": "https://slsa.dev/"},
  {"id": "a04-quote-schneier", "type": "quote", "sections": ["owasp-modal"],
   "owasp": "A04",
   "source": "Bruce Schneier · Applied Cryptography (contexto moderno)",
   "title": "«Anyone can invent a security system that they cannot break»",
   "excerpt": "Criptografia caseira e algoritmos obsoletos (MD5, RC4, ECB) aparecem em legado e em labs como insecurity.ts. A04 não exige quebrar AES — exige identificar crypto errada antes do vazamento offline.",
   "takeaway": "Use bibliotecas padrão e parâmetros atuais — nunca invente algoritmo.",
   "link": "https://owasp.org/Top10/2025/A04_2025-Cryptographic_Failures/"},
  {"id": "a06-quote-owasp", "type": "quote", "sections": ["owasp-modal"],
   "owasp": "A06",
   "source": "OWASP A06:2025 — Insecure Design",
   "title": "«Shift left — but not only to developers»",
   "excerpt": "Design inseguro inclui ausência de rate limit, workflows sem compensating control e confiança no client-side. WAF e patch não corrigem cupom infinito, race condition ou lógica de preço invertida.",
   "bullets": ["Abuse cases no refinamento", "Threat model por epic", "Revisão de UX de fluxos críticos"],
   "takeaway": "Se o bug é «by design», é A06 — não A05.",
   "link": "https://owasp.org/Top10/2025/A06_2025-Insecure_Design/"},
  {"id": "a07-quote-nist", "type": "quote", "sections": ["owasp-modal"],
   "owasp": "A07",
   "source": "NIST SP 800-63B",
   "title": "«Memorized secrets alone are insufficient»",
   "excerpt": "NIST recomenda MFA, rate limiting e detecção de credenciais comprometidas. A07 cobre JWT fraco, session fixation, credential stuffing e ausência de lockout — Juice Shop concentra vários em lib/insecurity.ts.",
   "takeaway": "Password policy sem MFA é controlo incompleto em 2025.",
   "link": "https://pages.nist.gov/800-63-4/"},
  {"id": "a07-mencao-hunt", "type": "mencao", "sections": ["owasp-modal"],
   "owasp": "A07",
   "author": "Troy Hunt",
   "source": "Menção · Credential stuffing",
   "title": "1,4 bilhão de credenciais vazadas no HIBP",
   "excerpt": "Hunt mantém o maior agregador público de breaches — credential stuffing funciona porque usuários reutilizam senhas e sistemas não têm rate limit nem MFA. Change Healthcare e Snowflake são casos em escala enterprise.",
   "stats": [("14B+", "Contas HIBP"), ("A07", "OWASP")],
   "takeaway": "Integre HIBP API ou similar no login — bloqueie senha já vazada.",
   "link": "https://haveibeenpwned.com/"},
  {"id": "a08-quote-codecov", "type": "quote", "sections": ["owasp-modal"],
   "owasp": "A08",
   "source": "Codecov incident report",
   "title": "«Integrity of the tooling pipeline is foundational»",
   "excerpt": "Após o breach, a lição publicada foi verificar integridade de scripts de CI/CD — hash, assinatura, ambiente isolado. Um único bash uploader modificado exfiltrou secrets de milhares de pipelines.",
   "takeaway": "Trate CI como tier-0 — mesma segurança de produção.",
   "link": "https://about.codecov.io/security-update"},
  {"id": "a09-quote-sans", "type": "quote", "sections": ["owasp-modal"],
   "owasp": "A09",
   "source": "SANS · Logging and Monitoring",
   "title": "«Prevention is ideal, but detection is a must»",
   "excerpt": "Sem detecção, o atacante permanece meses no ambiente (MTTI de 277 dias no IBM). A09:2025 renomeia a categoria para Logging and Alerting — armazenar terabyte de log sem alerta não é controle.",
   "bullets": ["Alertas com owner e runbook", "Correlação auth + data access", "Teste de alerta trimestral"],
   "takeaway": "Se ninguém responde ao alerta, o controle não existe.",
   "link": "https://www.sans.org/"},
  {"id": "a10-quote-microsoft", "type": "quote", "sections": ["owasp-modal"],
   "owasp": "A10",
   "source": "Microsoft SDL · Secure coding",
   "title": "«Fail securely — assume every input will eventually be hostile»",
   "excerpt": "Error handlers que fazem fail-open (liberam acesso em exceção), vazam stack trace ou deixam transação inconsistente são A10. Heartbleed mostrou que parsing de baixo nível também entra nesta categoria.",
   "takeaway": "Catch genérico que retorna 200 OK é vulnerabilidade de design.",
   "link": "https://www.microsoft.com/en-us/securityengineering/sdl"},

  # ── CWE modais — expandir cobertura ──
  {"id": "cwe20-quote", "type": "quote", "sections": ["cwe-modal"],
   "cwe": "CWE-20", "owasp": "A06",
   "source": "MITRE CWE-20",
   "title": "«Improper Input Validation is a root weakness»",
   "excerpt": "CWE-20 é pai conceitual de muitas injection — validação ausente ou no client-side só desloca o bug. Desceu 6 posições no TOP 25 2025 mas permanece onipresente em APIs que confiam no schema do frontend.",
   "takeaway": "Validar no servidor, na fronteira do trust boundary.",
   "link": "https://cwe.mitre.org/data/definitions/20.html"},
  {"id": "cwe787-highlight", "type": "highlight", "sections": ["cwe-modal"],
   "cwe": "CWE-787", "owasp": "A10",
   "source": "MITRE CWE TOP 25 2025",
   "title": "OOB Write caiu para #5 — ainda crítico em nativos",
   "excerpt": "CWE-787 permanece no top 5 apesar da queda. Bindings Node nativos, parsers de imagem/PDF e libs C/C++ em dependências trazem memory corruption para apps «só web».",
   "stats": [("#5", "Ranking 2025"), ("12", "KEV entries"), ("A10", "OWASP")],
   "takeaway": "Saiba quais deps nativas seu Node/Python importa.",
   "link": "https://cwe.mitre.org/data/definitions/787.html"},
  {"id": "cwe306-caso", "type": "caso", "sections": ["cwe-modal"],
   "cwe": "CWE-306", "owasp": "A07",
   "source": "Juice Shop · admin route",
   "title": "Missing Authentication em /rest/admin",
   "excerpt": "Juice Shop expõe application-configuration sem token — reproduz CWE-306 em segundos com curl. O mesmo padrão aparece em Snowflake (sem MFA), Change Healthcare (Citrix) e dezenas de APIs admin sem auth.",
   "bullets": ["curl http://localhost:3000/rest/admin/application-configuration", "Mapeie rotas admin no OpenAPI", "Middleware auth em prefix /admin"],
   "takeaway": "Enumere rotas sensíveis — não assuma que «está no backend interno».",
   "link": "https://cwe.mitre.org/data/definitions/306.html"},
  {"id": "cwe352-mencao", "type": "mencao", "sections": ["cwe-modal"],
   "cwe": "CWE-352", "owasp": "A06",
   "author": "OWASP CSRF Prevention Cheat Sheet",
   "source": "Menção · CSRF",
   "title": "SameSite cookies não substituem token anti-CSRF",
   "excerpt": "O cheat sheet OWASP lista defesa em profundidade: token synchronizer, double-submit, SameSite=Strict/Lax conforme fluxo. CWE-352 liga design (A06) e implementação — state-changing POST sem proteção continua comum.",
   "takeaway": "Todo POST/PUT/DELETE autenticado precisa de defesa CSRF explícita.",
   "link": "https://cheatsheetseries.owasp.org/cheatsheets/Cross-Site_Request_Forgery_Prevention_Cheat_Sheet.html"},
  {"id": "cwe416-highlight", "type": "highlight", "sections": ["cwe-modal"],
   "cwe": "CWE-416", "owasp": "A10",
   "source": "CISA KEV · Memory safety",
   "title": "Use-After-Free — 14 CVEs ativamente explorados",
   "excerpt": "CWE-416 subiu no radar com exploits em browsers e libs nativas. Para devs de aplicação web, o paralelo é gerenciar lifecycle de objetos em bindings nativos e parsers — não só JavaScript.",
   "takeaway": "Atualize Chromium/Electron e deps com FFI — UAF não é só kernel.",
   "link": "https://cwe.mitre.org/data/definitions/416.html"},
  {"id": "cwe125-caso", "type": "caso", "sections": ["cwe-modal"],
   "cwe": "CWE-125", "owasp": "A10",
   "source": "Heartbleed · CVE-2014-0160",
   "title": "Out-of-bounds Read — 500k+ servidores expostos",
   "excerpt": "Um heartbeat TLS mal validado vazou até 64KB de memória por request. Certificados, chaves e sessões saíram sem log de acesso — detecção (A09) também falhou em massa.",
   "stats": [("64KB", "Por request"), ("500k+", "Servidores"), ("A10", "OWASP")],
   "takeaway": "Libs críticas (TLS, crypto, parsing) exigem patch emergencial global.",
   "link": "https://nvd.nist.gov/vuln/detail/CVE-2014-0160"},
  {"id": "cwe77-highlight", "type": "highlight", "sections": ["cwe-modal"],
   "cwe": "CWE-77", "owasp": "A05",
   "source": "MITRE CWE TOP 25 2025",
   "title": "Command Injection — maior queda do ranking (−10)",
   "excerpt": "CWE-77 caiu 10 posições — frameworks modernos reduziram exec() direto. Cuidado: wrappers shell em Python/Node, pipelines CI e ferramentas DevOps mantêm a superfície viva.",
   "takeaway": "Nunca passe input do usuário para shell — use APIs sem spawn de shell.",
   "link": "https://cwe.mitre.org/data/definitions/77.html"},
  {"id": "cwe200-excerpt", "type": "excerpt", "sections": ["cwe-modal"],
   "cwe": "CWE-200", "owasp": "A02",
   "source": "OWASP Testing Guide · Information Exposure",
   "title": "Exposure não é só «dados vazados» — é qualquer info útil ao atacante",
   "excerpt": "Stack traces, versões de framework, paths internos e logs verbosos são CWE-200. First American (885M docs) e Power Apps (38M) são exposição sem exploit sofisticado — apenas ID sequencial ou lista pública.",
   "takeaway": "Erro 500 genérico no cliente; detalhe só no log server-side redigido.",
   "link": "https://owasp.org/www-project-web-security-testing-guide/"},

  # ── Hubs expandidos ──
  {"id": "owasp-hub-quote", "type": "quote", "sections": ["owasp-hub"],
   "source": "Jeff Williams · OWASP Top 10 creator",
   "title": "«The Top 10 is about raising awareness across the entire organization»",
   "excerpt": "O Top 10 nasceu para alinhar dev, QA, ops e negócio num vocabulário comum de risco. Os modais desta seção adicionam camada técnica (CWE, ASVS, WSTG) sem perder esse objetivo de awareness.",
   "takeaway": "Apresente A01–A10 para stakeholders — traduza em impacto de negócio.",
   "link": "https://owasp.org/Top10/2025/"},
  {"id": "ponte-owasp-quote", "type": "quote", "sections": ["ponte-owasp-cwe"],
   "owasp": "A05", "cwe": "CWE-79",
   "source": "OWASP + MITRE",
   "title": "Mesmo defeito, dois vocabulários",
   "excerpt": "«Injection can occur in many contexts — SQL, LDAP, XPath, NoSQL, OS command, SMTP header, expression language.» O OWASP agrupa o risco de negócio; o CWE nomeia a fraqueza no código. A matriz que você acabou de ver une os dois.",
   "takeaway": "Ao sair do hub OWASP para o CWE, busque a mesma correlação no modal.",
   "link": "https://owasp.org/Top10/2025/A05_2025-Injection/"},
  {"id": "ponte-cwe-mencao", "type": "mencao", "sections": ["ponte-owasp-cwe"],
   "author": "Robert C. Seacord · CERT",
   "source": "Menção · Secure coding",
   "title": "Fraqueza enumerada ≠ vulnerabilidade explorada",
   "excerpt": "Seacord enfatiza que CWE descreve classe de defeito — exploitabilidade depende de contexto, exposição e controles compensatórios. O TOP 25 MITRE prioriza prevalência em CVEs, não severidade no seu app específico.",
   "takeaway": "Use o score MITRE para estudo; use seu SAST/DAST para sprint.",
   "link": "https://wiki.sei.cmu.edu/confluence/display/c/SEI+CERT+Coding+Standards"},
  {"id": "cwe-hub-quote-mitre", "type": "quote", "sections": ["cwe-hub"],
   "source": "MITRE CWE Program",
   "title": "«CWE helps describe what went wrong»",
   "excerpt": "«Common Weakness Enumeration (CWE) is a community-developed list of software and hardware weakness types. It serves as a common language for describing the root cause of vulnerabilities.» Use ao lado do CVE: CVE é instância, CWE é classe.",
   "bullets": ["CVE → instância específica (patch)", "CWE → padrão no código (fix pattern)", "OWASP → risco de negócio (prioridade)"],
   "takeaway": "Nos relatórios, escreva CWE na causa raiz e OWASP no impacto.",
   "link": "https://cwe.mitre.org/about/"},
]