# CWE TOP 25 2025 — conteúdo completo para todas as 25 fraquezas
CWE_TOP25_FULL = [
  {"rank":1,"id":"CWE-79","name":"Cross-site Scripting (XSS)","name_pt":"Cross-site Scripting (XSS)",
   "score":60.38,"kev":7,"trend":"0","owasp":["A05"],
   "p":["CWE-79 lidera o TOP 25 MITRE 2025 com score 60,38 — mais que o dobro do segundo colocado. A fraqueza nasce quando dados não confiáveis entram no DOM sem encoding adequado ao contexto (HTML, atributo, JavaScript, URL).","Existem três variantes principais: reflected (resposta imediata), stored (persistido no servidor) e DOM-based (sink no client, sem round-trip). Em SPAs Angular/React, DOM XSS via bypass de sanitização é o vetor mais comum em pentests corporativos.","No ecossistema Juice Shop, buscas e feedbacks renderizam input sem escape. O challenge DOM XSS demonstra que sanitização parcial é pior que ausência — passa falso negativo em scanners."],
   "cases":[("British Airways Magecart, 2018","380k cartões","XSS em checkout third-party"),("Sam's Club, 2023","Skimmer via XSS","Supply chain script")],
   "det":["Mapear sources→sinks no código (Semgrep/CodeQL)","CSP report-only coletando violações","DOM Invader no Burp para sinks","Fuzzing de contexto HTML/attr/JS"],
   "mit":["OWASP XSS Prevention Cheat Sheet por contexto","CSP: default-src 'self'; script-src 'nonce-…'","HttpOnly + Secure + SameSite em cookies","DOMPurify com allowlist mínima"],
   "tools":["Burp DOM Invader","OWASP ZAP","Semgrep"],"juice":"feedback_xss",
   "refs":[("CWE-79","https://cwe.mitre.org/data/definitions/79.html"),("XSS Prevention","https://cheatsheetseries.owasp.org/cheatsheets/Cross_Site_Scripting_Prevention_Cheat_Sheet.html")]},
  {"rank":2,"id":"CWE-89","name":"SQL Injection","name_pt":"Injeção SQL",
   "score":28.72,"kev":4,"trend":"+1","owasp":["A05"],
   "p":["Segunda posição com score 28,72. A query SQL é montada por concatenação — o padrão clássico que prepared statements eliminam desde 2004, mas que persiste em ORMs mal utilizados (sequelize.query raw, ORDER BY dinâmico).","No Juice Shop, routes/login.ts linha 34 concatena email e password diretamente na query. routes/search.ts linha 20 expõe UNION-based injection no campo de busca.","Impacto: leitura de tabelas inteiras, bypass de autenticação, escrita e em alguns SGBDs RCE via xp_cmdshell ou INTO OUTFILE."],
   "cases":[("MOVEit, 2023","2.500+ orgs","Zero-day SQLi"),("Heartland Payment, 2008","130M cartões","Clássico SQLi")],
   "det":["sqlmap com --risk 3 --level 5 em staging","grep sequelize.query / createQueryBuilder raw","Error-based: provocar syntax error","Time-based blind em endpoints lentos"],
   "mit":["Parameterized queries / bind variables","ORM sem raw SQL em paths de usuário","Least privilege no usuário DB","WAF ModSecurity CRS rule 942"],
   "tools":["sqlmap","Semgrep","CodeQL"],"juice":"login_sql",
   "refs":[("CWE-89","https://cwe.mitre.org/data/definitions/89.html"),("SQLi Prevention","https://cheatsheetseries.owasp.org/cheatsheets/SQL_Injection_Prevention_Cheat_Sheet.html")]},
  {"rank":3,"id":"CWE-352","name":"Cross-Site Request Forgery","name_pt":"Cross-Site Request Forgery (CSRF)",
   "score":13.64,"kev":0,"trend":"+1","owasp":["A06"],
   "p":["Score 13,64. O browser da vítima envia request autenticado para ação que ela não intencionou. APIs que usam apenas cookies de sessão sem token anti-CSRF são vulneráveis.","SameSite=Lax mitiga GET; POST cross-origin ainda exige token synchronizer ou double-submit cookie.","Em Juice Shop, mutações sem CSRF token permitem forjar transferências e alterações de perfil a partir de página maliciosa."],
   "cases":[("Router CSRF wave, 2014","Milhões de routers","Config change"),("Instagram, 2015","Ações em massa","CSRF em API")],
   "det":["Verificar presença de token em forms POST","Testar cross-origin com Origin diferente","Review SameSite cookie attribute"],
   "mit":["Anti-CSRF token por sessão","SameSite=Strict em cookies sensíveis","Verificar Origin/Referer header","Re-autenticação para ações críticas"],
   "tools":["Burp CSRF PoC generator","OWASP ZAP"],"juice":"csrf_transfer",
   "refs":[("CWE-352","https://cwe.mitre.org/data/definitions/352.html"),("CSRF Prevention","https://cheatsheetseries.owasp.org/cheatsheets/Cross-Site_Request_Forgery_Prevention_Cheat_Sheet.html")]},
  {"rank":4,"id":"CWE-862","name":"Missing Authorization","name_pt":"Autorização Ausente",
   "score":13.28,"kev":0,"trend":"+5","owasp":["A01"],
   "p":["Subiu 5 posições — o maior salto do ranking 2025. O endpoint executa sem verificar se o caller tem permissão. Diferente de autenticação: o usuário está logado, mas acessa recurso alheio.","BOLA (Broken Object Level Authorization) da OWASP API Top 10 é a manifestação em REST. Juice Shop basket.ts retorna cesta por ID sem checar user.bid.","94% dos apps testados pelo OWASP apresentam alguma falha de access control em pentests recentes."],
   "cases":[("Optus, 2022","11,2M clientes","API sem authZ"),("USPS, 2018","60M registros","API Informed Visibility")],
   "det":["Trocar IDs sequenciais: /api/order/1001 → 1002","Acessar admin endpoints com token de user","GraphQL: campos sem @auth","Mass assignment de role"],
   "mit":["Checagem server-side em TODA operação","Policy engine (OPA, Cedar)","Testes automatizados por role matrix","Log de 403 com alerta"],
   "tools":["OWASP ZAP","Postman","AuthZEN"],"juice":"basket_idor",
   "refs":[("CWE-862","https://cwe.mitre.org/data/definitions/862.html"),("API1 BOLA","https://owasp.org/API-Security/editions/2023/en/0xa1-broken-object-level-authorization/")]},
  {"rank":5,"id":"CWE-787","name":"Out-of-bounds Write","name_pt":"Escrita Fora dos Limites (OOB Write)",
   "score":12.68,"kev":12,"trend":"-3","owasp":["A10"],
   "p":["Score 12,68 com 12 CVEs no KEV. Escrita além dos limites de buffer em C/C++. Base de RCE em software nativo, kernels e firmware.","Menos comum em web puro, mas crítico em extensões nativas, parsers (imagem, PDF) e IoT. Heartbleed era OOB read; exploits modernos combinam read+write.","Relaciona-se a A10 Mishandling of Exceptional Conditions quando bounds check falha silenciosamente."],
   "cases":[("OpenSSL Heartbleed, 2014","OOB read","500k servers"),("Stagefright, 2015","Android RCE","Media parser")],
   "det":["ASAN/MSAN em CI para código nativo","Fuzzing AFL++ em parsers","Code review de memcpy/strcpy"],
   "mit":["Bounds-checked APIs (memcpy_s)","Memory-safe languages (Rust)","Stack canaries + ASLR + DEP","Fuzzing contínuo"],
   "tools":["AFL++","Valgrind","CodeQL"],"juice":None,
   "refs":[("CWE-787","https://cwe.mitre.org/data/definitions/787.html")]},
  {"rank":6,"id":"CWE-22","name":"Path Traversal","name_pt":"Path Traversal",
   "score":8.99,"kev":10,"trend":"-1","owasp":["A01"],
   "p":["Score 8,99. Sequências ../ permitem leitura de arquivos fora do diretório permitido. Comum em download de relatórios, importação de templates e APIs de arquivo.","Em Juice Shop, challenges de directory traversal exploram /ftp e parâmetros de download sem canonicalização de path.","10 CVEs no KEV — frequentemente encadeado com information disclosure para obter credenciais."],
   "cases":[("Zip Slip, 2018","Milhares de libs","../ em unzip"),("Citrix ADC, 2019","CVE-2019-19781","Arbitrary read")],
   "det":["Payload: ../../../etc/passwd","URL encoding duplo: ..%252f","Unicode normalization bypass"],
   "mit":["Canonicalize path e verificar prefixo permitido","chroot ou jail por tenant","Deny list de .. e symlinks"],
   "tools":["Burp Intruder","ffuf"],"juice":"path_ftp",
   "refs":[("CWE-22","https://cwe.mitre.org/data/definitions/22.html")]},
  {"rank":7,"id":"CWE-416","name":"Use After Free","name_pt":"Use After Free",
   "score":8.47,"kev":14,"trend":"+1","owasp":["A10"],
   "p":["Score 8,47 com 14 KEV — classe dominante em exploits de browser e kernel. Ponteiro usado após memória liberada.","Exploração requer heap grooming; em segurança de aplicações web aparece em bindings nativos (Node addons, Python C extensions).","Correlação com A10: estado inconsistente após erro pode deixar referência dangling."],
   "cases":[("Chrome UAF exploits, ongoing","RCE em browser","V8/Blink"),("SolarWinds SUNBURST, 2020","Supply chain","Nativo + managed")],
   "det":["ASAN detecta UAF em testes","Static analysis em código C/C++","Fuzzing com sanitizers"],
   "mit":["Smart pointers em C++","Rust ownership model","Patch management acelerado"],
   "tools":["ASAN","Coverity"],"juice":None,
   "refs":[("CWE-416","https://cwe.mitre.org/data/definitions/416.html")]},
  {"rank":8,"id":"CWE-125","name":"Out-of-bounds Read","name_pt":"Leitura Fora dos Limites (OOB Read)",
   "score":7.88,"kev":3,"trend":"-2","owasp":["A10"],
   "p":["Score 7,88. Leitura além do buffer vaza memória adjacente — tokens, chaves, ponteiros para exploit chain.","Heartbleed (OpenSSL) é o exemplo paradigmático: 64KB de memória vazada por request malformado.","Em aplicações web, parsers de imagem/PDF em código nativo são vetores indiretos."],
   "cases":[("Heartbleed, 2014","Chaves TLS vazadas","OpenSSL"),("WhatsApp, 2019","NSO exploit","Buffer read")],
   "det":["Fuzzing de parsers binários","Valgrind memcheck","Bounds analysis"],
   "mit":["Input length validation","Safe parsing libraries","Sandbox de parsers"],
   "tools":["AFL++","Valgrind"],"juice":None,
   "refs":[("CWE-125","https://cwe.mitre.org/data/definitions/125.html")]},
  {"rank":9,"id":"CWE-78","name":"OS Command Injection","name_pt":"Injeção de Comando OS",
   "score":7.85,"kev":20,"trend":"-2","owasp":["A05"],
   "p":["Score 7,85 com 20 KEV — um dos mais explorados ativamente. Input passa para exec(), system(), popen() ou subprocess shell=True.","Comum em ferramentas DevOps web (ping, traceroute, conversores), painéis de admin e CI triggers.","Mitigação: APIs sem shell (subprocess list, sem shell=True), allowlist de argumentos."],
   "cases":[("Shellshock, 2014","Milhões de servers","Bash env"),("Equifax Struts, 2017","RCE","OGNL/command")],
   "det":["Payload: ; id | whoami `id`","Time delay: & sleep 10 &","Out-of-band: curl attacker.com"],
   "mit":["Nunca passar input para shell","Allowlist de comandos fixos","Sandbox/containers sem network"],
   "tools":["Commix","Burp"],"juice":None,
   "refs":[("CWE-78","https://cwe.mitre.org/data/definitions/78.html")]},
  {"rank":10,"id":"CWE-94","name":"Code Injection","name_pt":"Injeção de Código",
   "score":7.57,"kev":7,"trend":"+1","owasp":["A05"],
   "p":["Score 7,57. Input gera código executável — eval(), Function(), template engines server-side, EL injection.","Juice Shop fileUpload.ts usa vm.runInContext com yaml.load — injeção indireta via deserialização.","Diferente de command injection: executa no runtime da aplicação (Node, Java, .NET)."],
   "cases":[("Confluence OGNL, 2022","RCE massivo","Template injection"),("Apache Struts, 2017","Equifax","OGNL")],
   "det":["grep eval( / new Function( / vm.run","Template injection fuzzing","SAST taint analysis"],
   "mit":["Proibir eval e dynamic code execution","Sandbox com timeout e sem require","Template engines em modo logic-less"],
   "tools":["Semgrep","Burp SSTI scanner"],"juice":"file_yaml_rce",
   "refs":[("CWE-94","https://cwe.mitre.org/data/definitions/94.html")]},
  {"rank":11,"id":"CWE-120","name":"Classic Buffer Overflow","name_pt":"Buffer Overflow Clássico",
   "score":6.96,"kev":0,"trend":"N/A","owasp":["A10"],
   "p":["Score 6,96. memcpy/strcpy sem verificação de tamanho — vulnerabilidade fundacional ensinada em sistemas operacionais.","Reentrada no TOP 25 2025 após separação de variantes stack/heap.","Relevante para firmware, drivers e serviços legados expostos por APIs web via JNI/FFI."],
   "cases":[("Morris Worm, 1988","Primeiro worm","gets() overflow"),("Code Red, 2001","IIS","Buffer overflow")],
   "det":["Static analysis strcpy/memcpy","Canary violations em runtime","Retrofit de código legado"],
   "mit":["strncpy, snprintf, bounded copies","Compiladores com FORTIFY_SOURCE","Migração para memory-safe code"],
   "tools":["Coverity","Clang analyzer"],"juice":None,
   "refs":[("CWE-120","https://cwe.mitre.org/data/definitions/120.html")]},
  {"rank":12,"id":"CWE-434","name":"Unrestricted Upload","name_pt":"Upload Irrestrito de Arquivo",
   "score":6.87,"kev":4,"trend":"-2","owasp":["A01","A08"],
   "p":["Score 6,87. Servidor aceita .php, .jsp, .aspx sem validar tipo, conteúdo e local de armazenamento.","Juice Shop fileUpload.ts valida extensão de forma fraca — bypass com polyglot e double extension.","Upload fora de webroot ou sem execução de script mitiga impacto, mas não elimina stored XSS."],
   "cases":[("Apache Struts upload, 2018","RCE","Content-Type bypass"),("Ghostscript, 2018","RCE via SVG","Upload chain")],
   "det":["Upload webshell com double ext .php.jpg","Content-Type vs magic bytes mismatch","Path traversal em filename"],
   "mit":["Allowlist de extensões + verificação magic bytes","Armazenar fora de docroot","Renomear arquivo server-side (UUID)","Scan antivirus em pipeline"],
   "tools":["Burp Upload scanner"],"juice":"file_yaml_rce",
   "refs":[("CWE-434","https://cwe.mitre.org/data/definitions/434.html")]},
  {"rank":13,"id":"CWE-476","name":"NULL Pointer Dereference","name_pt":"Desreferência de Ponteiro NULL",
   "score":6.41,"kev":0,"trend":"+8","owasp":["A10"],
   "p":["Score 6,41 — subiu 8 posições, maior ascensão relativa. Crash por dereference de NULL — DoS ou, em casos raros, execução.","Comum em código C/C++ após refatoração; em Java vira NullPointerException — menos crítico mas indica fail-open.","Correlação A10: exceção não tratada após NULL check ausente vaza stack trace."],
   "cases":[("Linux kernel NULL deref, vários","DoS local","Drivers"),("Android system_server","Crash loop","NULL ptr")],
   "det":["Static null analysis","Fuzzing com fault injection","Crash dumps em produção"],
   "mit":["Defensive null checks","Optional types (Java, Kotlin)","Rust Option<T>"],
   "tools":["Infer","SpotBugs"],"juice":None,
   "refs":[("CWE-476","https://cwe.mitre.org/data/definitions/476.html")]},
  {"rank":14,"id":"CWE-121","name":"Stack-based Buffer Overflow","name_pt":"Stack Buffer Overflow",
   "score":5.75,"kev":4,"trend":"N/A","owasp":["A10"],
   "p":["Score 5,75. Overflow na pilha — permite sobrescrever return address para ROP chain.","Base de exploits clássicos; mitigado por ASLR, DEP, stack canaries — mas bypasses existem.","Relevante em binários acoplados a aplicações web (conversores, agents)."],
   "cases":[("Slammer worm, 2003","SQL Server","Stack overflow"),("WannaCry, 2017","EternalBlue","SMB")],
   "det":["checksec em binários","ROP gadget search","Canary leak attempts"],
   "mit":["Stack canaries (-fstack-protector)","ASLR + DEP/NX","Migração para linguagens safe"],
   "tools":["Ghidra","pwntools"],"juice":None,
   "refs":[("CWE-121","https://cwe.mitre.org/data/definitions/121.html")]},
  {"rank":15,"id":"CWE-502","name":"Deserialization of Untrusted Data","name_pt":"Desserialização de Dados Não Confiáveis",
   "score":5.23,"kev":11,"trend":"+1","owasp":["A08"],
   "p":["Score 5,23 com 11 KEV. Objeto desserializado de fonte não confiável executa código via magic methods ou gadgets.","Java Commons Collections, .NET ViewState, Python pickle, PHP unserialize, Node node-serialize — cada ecossistema tem gadget chains.","Juice Shop: yaml.load em vm.runInContext — desserialização + code execution combinados."],
   "cases":[("Equifax Struts, 2017","RCE","Java deserialize"),("Apache Log4j adjacent patterns","Gadget chains","Libraries")],
   "det":["grep pickle.loads / ObjectInputStream / unserialize","Gadget chain scanners (ysoserial)","Monitor deserialization endpoints"],
   "mit":["Nunca desserializar input externo","JSON schema validation em vez de objetos","Allowlist de classes (Java ObjectInputFilter)","Assinatura digital de payload"],
   "tools":["ysoserial","SerialKiller"],"juice":"file_yaml_rce",
   "refs":[("CWE-502","https://cwe.mitre.org/data/definitions/502.html")]},
  {"rank":16,"id":"CWE-122","name":"Heap-based Buffer Overflow","name_pt":"Heap Buffer Overflow",
   "score":5.21,"kev":6,"trend":"N/A","owasp":["A10"],
   "p":["Score 5,21. Overflow no heap — exploração via heap spraying e metadata corruption.","Mais difícil que stack overflow mas prevalente em browsers e media parsers.","6 CVEs no KEV ativos em 2025."],
   "cases":[("V8 engine bugs","RCE Chrome","Heap OOB"),("ImageMagick, 2016","ImageTragick","Heap overflow")],
   "det":["Heap sanitizer (H/W)","Fuzzing com libFuzzer","Taint tracking em allocações"],
   "mit":["Safe allocators (jemalloc hardening)","Memory-safe languages","Sandbox de processamento"],
   "tools":["GEF","AFL++"],"juice":None,
   "refs":[("CWE-122","https://cwe.mitre.org/data/definitions/122.html")]},
  {"rank":17,"id":"CWE-863","name":"Incorrect Authorization","name_pt":"Autorização Incorreta",
   "score":4.14,"kev":4,"trend":"+1","owasp":["A01"],
   "p":["Score 4,14. Checagem existe mas está errada — lógica invertida, comparação == vs ===, role string case-sensitive, JWT claim não validado.","Juice Shop Admin Section: verificação de role no client mas endpoint acessível. Five-Star Feedback: qualquer user deleta feedback.","Diferente de CWE-862 (ausente): aqui o desenvolvedor acreditou ter protegido."],
   "cases":[("Facebook View As, 2018","50M tokens","Role bug"),("GitHub, 2019","Repo access","Logic flaw")],
   "det":["Test matrix: user × role × resource × action","Diff de policies entre ambientes","Review de middleware order"],
   "mit":["Unit tests por combinação role/resource","Centralizar authZ em um módulo","Code review focado em condicionais de role"],
   "tools":["OWASP ZAP","Custom scripts"],"juice":"basket_idor",
   "refs":[("CWE-863","https://cwe.mitre.org/data/definitions/863.html")]},
  {"rank":18,"id":"CWE-20","name":"Improper Input Validation","name_pt":"Validação de Entrada Inadequada",
   "score":4.09,"kev":2,"trend":"-6","owasp":["A05","A06"],
   "p":["Score 4,09 — desceu 6 posições mas continua transversal. Raiz de quase toda injeção: validação ausente, incompleta ou apenas client-side.","Whitelist > blacklist. Validar tipo, tamanho, range, formato e semântica.","Juice Shop aceita registros sem validação de email, quantity negativa em basket — business logic flaws."],
   "cases":[("Integer overflow purchases, vários","Preço negativo","E-commerce"),("API mass assignment","Role escalation","JSON body")],
   "det":["Fuzzing de tipos: string onde espera int","Boundary values: MAX_INT, -1, 0","Unicode normalization"],
   "mit":["Schema validation (JSON Schema, Zod, Pydantic)","Server-side validation obrigatória","Allowlist de caracteres por campo"],
   "tools":["Schemathesis","Hypothesis"],"juice":"login_sql",
   "refs":[("CWE-20","https://cwe.mitre.org/data/definitions/20.html")]},
  {"rank":19,"id":"CWE-284","name":"Improper Access Control","name_pt":"Controle de Acesso Inadequado",
   "score":4.07,"kev":1,"trend":"N/A","owasp":["A01"],
   "p":["Score 4,07. Política de acesso não restringe atores não autorizados — umbrella term que inclui RBAC mal configurado e ACLs vazias.","Reentrada no TOP 25 como categoria explícita. Complementa CWE-862/863 com foco na política, não na implementação pontual.","Em microserviços, service-to-service auth frequentemente ausente dentro do cluster."],
   "cases":[("Capital One, 2019","IAM role too broad","Cloud policy"),("Azure AD misconfig, vários","Tenant crossover","Policy gap")],
   "det":["IAM policy review (Prowler, ScoutSuite)","Service mesh authZ audit","Kubernetes RBAC enumeration"],
   "mit":["Least privilege IAM","Network policies K8s","mTLS entre serviços"],
   "tools":["Prowler","kube-bench"],"juice":"basket_idor",
   "refs":[("CWE-284","https://cwe.mitre.org/data/definitions/284.html")]},
  {"rank":20,"id":"CWE-200","name":"Exposure of Sensitive Information","name_pt":"Exposição de Informação Sensível",
   "score":4.01,"kev":1,"trend":"-3","owasp":["A02","A09"],
   "p":["Score 4,01. Resposta HTTP, log ou erro expõe PII, tokens, stack traces ou dados de outros usuários.","Juice Shop: access.log com tokens JWT, /metrics e /promotion com dados internos.","LGPD Art. 46: incidente de exposição exige notificação à ANPD em cenários de risco."],
   "cases":[("First American, 2019","885M docs","Sem auth"),("Verizon DBIR leaks","Dados agregados","Misconfig")],
   "det":["grep console.log / print em código","Verificar 500 responses em produção","Scan de /.git, /backup, /.env"],
   "mit":["Redação de PII em logs","Generic error messages","DLP em saída de API"],
   "tools":["trufflehog","gitleaks"],"juice":"insecurity_md5",
   "refs":[("CWE-200","https://cwe.mitre.org/data/definitions/200.html")]},
  {"rank":21,"id":"CWE-306","name":"Missing Authentication","name_pt":"Autenticação Ausente",
   "score":3.47,"kev":11,"trend":"+4","owasp":["A07"],
   "p":["Score 3,47 com 11 KEV — subiu 4 posições. Função crítica acessível sem autenticação: admin panels, debug endpoints, APIs internas expostas.","Juice Shop Score Board e várias rotas /rest/admin acessíveis sem token em configurações default.","Diferente de broken auth: aqui não há nem tentativa de login.","OWASP A07:2025 mantém 36 CWEs nesta família; frameworks OAuth2/OIDC reduzem ocorrências mas endpoints legados e BFF mal configurados perpetuam CWE-306. Credential stuffing = 16% breaches (Verizon DBIR 2024)."],
   "cases":[("Microsoft Power Apps, 2021","38M registros","Anonymous access"),("Panera Bread, 2018","PII exposta","API sem auth")],
   "det":["Crawl de endpoints sem token","Swagger/OpenAPI exposure","Default credentials scan"],
   "mit":["Auth em todo endpoint não-público","Network segmentation","API gateway com auth obrigatório"],
   "tools":["ffuf","kiterunner"],"juice":"admin_config",
   "refs":[("CWE-306","https://cwe.mitre.org/data/definitions/306.html")]},
  {"rank":22,"id":"CWE-918","name":"Server-Side Request Forgery","name_pt":"Server-Side Request Forgery (SSRF)",
   "score":3.36,"kev":0,"trend":"-3","owasp":["A01"],
   "p":["Score 3,36. Servidor faz HTTP request para URL controlada pelo atacante — acessa metadata cloud (169.254.169.254), Redis interno, admin panels.","Capital One: SSRF → IAM credentials → 106M registros. Saiu do OWASP Top 10:2025 mas permanece no CWE TOP 25.","Blind SSRF via DNS callback ou timing; non-blind via response body."],
   "cases":[("Capital One, 2019","106M registros","AWS metadata"),("Shopify SSRF, 2017","Internal access","Webhook URL")],
   "det":["Payload: http://169.254.169.254/latest/meta-data/","DNS callback (Burp Collaborator)","Protocol smuggling: file://, gopher://"],
   "mit":["Allowlist de destinos e protocolos","Block link-local e RFC1918","Sem raw URL fetch de input do usuário"],
   "tools":["Burp Collaborator","SSRFmap"],"juice":"redirect_open",
   "refs":[("CWE-918","https://cwe.mitre.org/data/definitions/918.html"),("SSRF Prevention","https://cheatsheetseries.owasp.org/cheatsheets/Server_Side_Request_Forgery_Prevention_Cheat_Sheet.html")]},
  {"rank":23,"id":"CWE-77","name":"Command Injection","name_pt":"Injeção de Comando",
   "score":3.15,"kev":2,"trend":"-10","owasp":["A05"],
   "p":["Score 3,15 — desceu 10 posições mas ainda com 2 KEV. Generalização de injeção em interpreters de comando (não só OS shell).","Diferente de CWE-78: cobre qualquer command interpreter (SNMP, LDAP cmd, custom DSL).","Desceu porque ferramentas e frameworks modernos reduziram superfície — mas DevOps webhooks reintroduzem risco."],
   "cases":[("GitHub Actions injection, 2020+","CI RCE","Workflow cmd"),("VMware vCenter, 2021","RCE","Command injection")],
   "det":["Injectar em parâmetros de CLI tools","Pipeline YAML command injection","SNMP/LDAP command params"],
   "mit":["Parameterized APIs sem shell","Input sanitization por contexto","CI/CD secret isolation"],
   "tools":["Commix"],"juice":None,
   "refs":[("CWE-77","https://cwe.mitre.org/data/definitions/77.html")]},
  {"rank":24,"id":"CWE-639","name":"Authorization Bypass via User Key","name_pt":"Bypass de Autorização via Chave do Usuário",
   "score":2.62,"kev":0,"trend":"+6","owasp":["A01"],
   "p":["Score 2,62 — subiu 6 posições. ID controlado pelo usuário (userId, accountId, basketId) usado na query sem validar ownership.","Manifestação específica de BOLA. Juice Shop basket.ts é caso canônico: GET /rest/basket/{id} sem checar bid do token.","APIs GraphQL com filter userId passado pelo client são vetor frequente."],
   "cases":[("Instagram, 2018","Download de dados","userId param"),("USPS, 2018","60M","API key in URL")],
   "det":["Alterar userId/basketId/orderId em requests","GraphQL variables manipulation","UUID vs sequential ID enumeration"],
   "mit":["Derive user ID do token, nunca do request body","UUIDs não sequenciais","Server-side join com session user"],
   "tools":["Burp Autorize"],"juice":"basket_idor",
   "refs":[("CWE-639","https://cwe.mitre.org/data/definitions/639.html")]},
  {"rank":25,"id":"CWE-770","name":"Allocation Without Limits","name_pt":"Alocação Sem Limites",
   "score":2.54,"kev":0,"trend":"+1","owasp":["A06"],
   "p":["Score 2,54. Sem throttling: brute force de senha, account enumeration, resource exhaustion, expensive API calls ilimitados.","Juice Shop: sem rate limit no login (password spraying), CAPTCHA bypassável, feedback flood.","Relaciona-se a A06 Insecure Design — limites são decisão arquitetural, não patch."],
   "cases":[("GitHub password spray, ongoing","Credential stuffing","Sem rate limit"),("Dyn DDoS, 2016","IoT botnet","Resource flood")],
   "det":["Load test com login burst","Verificar 429 responses","Monitor CPU/mem por request"],
   "mit":["Rate limit por IP + user (token bucket)","CAPTCHA server-side após N falhas","WAF rate rules","Circuit breaker em APIs caras"],
   "tools":["k6","wrk"],"juice":"deluxe_coupon",
   "refs":[("CWE-770","https://cwe.mitre.org/data/definitions/770.html")]},
]