# OWASP Top 10 2025 — dados densos (importado por generate_html.py)
import textwrap

JUICE = {
  "login_sql": {"file":"routes/login.ts","line":34,"challenge":"Login Admin / Bender / Jim",
    "code":"models.sequelize.query(`SELECT * FROM Users WHERE email = '${req.body.email || ''}' AND password = '${security.hash(req.body.password || '')}' AND deletedAt IS NULL`, { model: UserModel, plain: true })",
    "fix":"UserModel.findOne({ where: { email: req.body.email, password: security.hash(req.body.password), deletedAt: null } })",
    "payload":"' OR 1=1--","steps":["POST /rest/user/login com DevTools aberto","Injete payload no campo email","Query concatenada autentica sem senha válida","Mapeie para CWE-89 e A05"]},
  "basket_idor": {"file":"routes/basket.ts","line":19,"challenge":"View Basket of another User",
    "code":"const id = req.params.id\nconst basket = await BasketModel.findOne({ where: { id }, include: [...] })\nres.json(utils.queryResultToJson(basket))  // sem validar user.bid",
    "fix":"if (parseInt(id,10) !== user.bid) return res.status(403).json({ error: 'Forbidden' })",
    "payload":"GET /rest/basket/{id_alheio}","steps":["Login e anote bid do response","Altere ID na URL do carrinho","JSON de outro usuário é retornado","CWE-639 + CWE-862"]},
  "search_sqli": {"file":"routes/search.ts","line":20,"challenge":"UNION SQL Injection",
    "code":"models.sequelize.query(`SELECT * FROM Products WHERE ((name LIKE '%${criteria}%' OR description LIKE '%${criteria}%') AND deletedAt IS NULL) ORDER BY name`)",
    "fix":"ProductModel.findAll({ where: { name: { [Op.like]: `%${criteria}%` } } })",
    "payload":"')) UNION SELECT email,password,null,null,null FROM Users--","steps":["Campo de busca da loja","Payload UNION para exfiltrar Users","Segundo payload para sqlite_master","Documente schema exposto"]},
  "insecurity_md5": {"file":"lib/insecurity.ts","line":47,"challenge":"Weird Crypto",
    "code":"export const hash = (data: string) => crypto.createHash('md5').update(data).digest('hex')",
    "fix":"bcrypt.hashSync(data, 12) // ou Argon2id",
    "payload":"N/A","steps":["Abra lib/insecurity.ts no clone local","Confirme MD5 para senhas","Compare ASVS 2.4.1","Relacione A04"]},
  "insecurity_jwt": {"file":"lib/insecurity.ts","line":52,"challenge":"Unsigned JWT",
    "code":"export const authorize = (user={}) => jwt.sign(user, privateKey, { expiresIn:'6h', algorithm:'RS256' })\nexport const verify = (token) => token ? jws.verify(token, publicKey) : false",
    "fix":"jwt.verify(token, publicKey, { algorithms: ['RS256'] })",
    "payload":"alg:none no header JWT","steps":["Capture token no login","Altere alg para none","Acesse rota admin","A07 + A08"]},
  "redirect_open": {"file":"lib/insecurity.ts","line":95,"challenge":"Allowlist Redirect Bypass",
    "code":"allowed = allowed || url.includes(allowedUrl)  // substring, não origin",
    "fix":"const u = new URL(url); return ALLOWED.has(u.origin)",
    "payload":"https://trusted.com.evil/phish","steps":["Endpoint /redirect","Bypass por substring","A01/A06 design flaw"]},
  "file_yaml_rce": {"file":"routes/fileUpload.ts","line":72,"challenge":"YAML Deserialization",
    "code":"vm.runInContext('JSON.stringify(yaml.load(data))', sandbox, { timeout: 2000 })",
    "fix":"Rejeitar YAML; parser sem vm; limite de tamanho",
    "payload":"complaint.yml recursivo","steps":["Upload .yaml em complaints","yaml.load em vm","CWE-502 + A08"]},
}

CORRELATIONS = [
  ("A01","CWE-862",3,"Missing Authorization — IDOR em APIs REST"),
  ("A01","CWE-863",3,"Authorization logic invertida ou incompleta"),
  ("A01","CWE-639",3,"Chave user-controlled (basketId) sem ownership"),
  ("A01","CWE-284",2,"Access control policy ausente"),
  ("A01","CWE-22",2,"Path traversal em download de arquivos"),
  ("A01","CWE-918",2,"SSRF para metadata cloud"),
  ("A01","CWE-434",2,"Upload sem restrição"),
  ("A02","CWE-200",3,"Exposição por config (logs, buckets)"),
  ("A02","CWE-16",2,"Configuration genérica"),
  ("A03","CWE-829",3,"Dependência não confiável"),
  ("A03","CWE-502",2,"Pacote malicioso"),
  ("A04","CWE-327",3,"Algoritmo quebrado (MD5)"),
  ("A04","CWE-798",3,"Credenciais hardcoded"),
  ("A05","CWE-79",3,"XSS — #1 CWE 2025"),
  ("A05","CWE-89",3,"SQLi — login.ts, search.ts"),
  ("A05","CWE-78",2,"OS command injection"),
  ("A05","CWE-94",2,"Code injection"),
  ("A05","CWE-77",2,"Command injection"),
  ("A05","CWE-20",2,"Input validation ausente"),
  ("A06","CWE-352",3,"CSRF por design"),
  ("A06","CWE-770",2,"Sem rate limit"),
  ("A07","CWE-306",3,"Função crítica sem auth"),
  ("A07","CWE-287",2,"Autenticação incorreta"),
  ("A08","CWE-502",3,"Deserialização insegura"),
  ("A09","CWE-200",2,"Logs expõem tokens"),
  ("A10","CWE-787",2,"OOB write"),
  ("A10","CWE-416",2,"Use-after-free"),
  ("A10","CWE-476",2,"NULL deref"),
  ("A10","CWE-209",3,"Stack trace em HTTP 500"),
]

OWASP_2021_VS_2025 = [
  ("A01","Broken Access Control","Broken Access Control","Mantido #1"),
  ("A02","Cryptographic Failures","Security Misconfiguration","Cripto desceu"),
  ("A03","Injection","Software Supply Chain","Nova supply chain"),
  ("A04","Insecure Design","Cryptographic Failures","Reposicionada"),
  ("A05","Security Misconfiguration","Injection","Injection desceu"),
  ("A06","Vulnerable Components","Insecure Design","Componentes→supply"),
  ("A07","Authentication Failures","Authentication Failures","Mantido"),
  ("A08","Software/Data Integrity","Software/Data Integrity","Mantido"),
  ("A09","Logging Failures","Logging and Alerting","Ênfase alertas"),
  ("A10","SSRF","Mishandling Exceptions","SSRF saiu; exceções entraram"),
]

OWASP_LIST = [
  {"id":"A01","pt":"Controle de Acesso Quebrado","en":"Broken Access Control",
   "p":[
     "Broken Access Control permanece na primeira posição do OWASP Top 10:2025. Em testes de penetração, falhas de autorização aparecem em praticamente todos os escopos web — não por ausência de login, mas porque a checagem de permissão não acompanha cada operação no servidor.",
     "IDOR (Insecure Direct Object Reference), BOLA em APIs, escalação vertical para rotas /admin e bypass de workflow são padrões recorrentes. O CWE-862 (Missing Authorization) subiu cinco posições no TOP 25 MITRE 2025, sinalizando que o mercado ainda subestima autorização server-side.",
     "No Juice Shop, routes/basket.ts retorna qualquer cesta pelo ID da URL sem validar ownership — reproduzível em 30 segundos com DevTools. O mesmo padrão destruiu dados de milhões em APIs REST mal modeladas.",
     "Dados oficiais OWASP 2025: 3,73% das 2,8M+ aplicações testadas tinham pelo menos uma das 40 CWEs desta categoria. SSRF (CWE-918) foi incorporado aqui — saiu como categoria autônoma do Top 10."
   ],
   "cwes":["CWE-862","CWE-863","CWE-639","CWE-284","CWE-22","CWE-918"],
   "cases":[("Optus API, 2022","11,2M clientes","GET sem authZ"),("Capital One, 2019","106M registros","SSRF→IAM role"),("Peloton, 2021","Exposição de PII","IDOR em API"),("Facebook, 2018","50M contas","View As bug")],
   "juice":["basket_idor","mass_assignment","path_ftp","ssrf_profile","redirect_open"],"det":["Mapa de endpoints × roles esperadas","Teste horizontal: trocar IDs de recursos","Teste vertical: acessar /admin sem role","Log de 403 e tentativas de escalação"],
   "test":["WSTG-ATHZ-01: Directory traversal","WSTG-ATHZ-02: Bypassing auth schema","WSTG-ATHZ-03: IDOR","WSTG-ATHZ-04: OAuth weaknesses"],
   "asvs":["V4.1 Access control enforcement","V4.2 Operation level access","V13.1 Generic webhook validation"],
   "prev":["Deny-by-default em middleware de autorização","Policy-as-code (OPA, Cedar)","Testes automatizados BOLA/BFLA (OWASP ZAP)","Segregação de tenants com row-level security"],
   "refs":[("OWASP A01:2025","https://owasp.org/Top10/2025/A01_2025-Broken_Access_Control/"),("CWE-862","https://cwe.mitre.org/data/definitions/862.html"),("OWASP API Security Top 10","https://owasp.org/API-Security/"),("Verizon DBIR 2024","https://www.verizon.com/business/resources/reports/dbir/"),("NIST SP 800-63B","https://pages.nist.gov/800-63-4/"),("PortSwigger IDOR","https://portswigger.net/web-security/access-control/idor")],
   "diff":"Mantido #1. SSRF saiu do Top 10 mas continua mapeado aqui via APIs que buscam URLs internas."},
  {"id":"A02","pt":"Configuração Insegura","en":"Security Misconfiguration",
   "p":[
     "Ambientes cloud com buckets públicos, headers de segurança ausentes, CORS * e painéis de administração expostos compõem a maior parte dos achados em auditorias de configuração. O Verizon DBIR 2024 atribui cerca de 15% dos incidentes web a misconfiguration.",
     "Diferente de vulnerabilidade de código, misconfiguration é corrigida por IaC, policy gates e hardening automatizado — mas só funciona se o baseline for testado continuamente.",
     "Juice Shop expõe diretórios /ftp, /encryptionkeys e package.json acessíveis — simulando deploy onde static files e artefatos de build ficaram no docroot.",
     "OWASP 2025: subiu de #5 (2021) para #2 — 3,00% das apps com falha em uma das 16 CWEs. Tendência explicada pelo aumento de comportamento configurável (cloud, K8s, feature flags) sem baseline automatizado."
   ],
   "cwes":["CWE-16","CWE-200","CWE-1188"],"cases":[("Microsoft Power Apps, 2021","38M registros","Listas públicas"),("Accenture AWS, 2017","Chaves API expostas","Bucket aberto"),("Twitch, 2021","Código fonte vazado","Config Git"),("Capital One WAF, 2019","Bypass de WAF","Regra mal configurada")],
   "juice":["access_log_leak","path_ftp","insecurity_md5"],"det":["Scanner CSP/headers (Mozilla Observatory)","CIS Benchmark compliance","Enumeração de superfície (ffuf, amass)","Review de Terraform/CloudFormation"],
   "test":["WSTG-CONF-01: Network infrastructure","WSTG-CONF-02: Security headers","WSTG-CONF-06: Test HTTP methods","WSTG-CONF-07: HSTS"],
   "asvs":["V14.4 HTTP security headers","V14.2 Dependency configuration","V1.1 Secure SDLC"],
   "prev":["CIS hardening automatizado no CI","CSP restritiva com nonce","Desabilitar métodos HTTP desnecessários","Secrets em vault, nunca em repo"],
   "refs":[("OWASP A02:2025","https://owasp.org/Top10/2025/A02_2025-Security_Misconfiguration/"),("CIS Benchmarks","https://www.cisecurity.org/cis-benchmarks"),("Mozilla Observatory","https://observatory.mozilla.org/"),("AWS Well-Architected SEC","https://docs.aws.amazon.com/wellarchitected/latest/security-pillar/")],
   "diff":"Subiu de A05:2021 para A02:2025 — reflexo de adoção cloud sem baseline."},
  {"id":"A03","pt":"Falhas na Cadeia de Suprimentos","en":"Software Supply Chain Failures",
   "p":[
     "Categoria nova em 2025, absorvendo 'Vulnerable Components' e expandindo para pipeline, dependências transitivas e integridade de build. SolarWinds (2020) e XZ Utils (2024) demonstram que um único artefato comprometido escala para milhares de vítimas.",
     "SBOM não é checklist: sem ele, incident response não sabe o que patchar. SLSA nível 3+ exige proveniência assinada e build hermético.",
     "No Juice Shop, package.json declara versões vulneráveis de propósito — exercício de correlacionar advisory npm com CVE e CVSS.",
     "OWASP 2025: categoria com 5 CWEs — menor presença nos dados de teste, mas maiores scores médios de exploit e impacto nas CVEs associadas. Vencedora da pesquisa comunitária; testes automatizados ainda não capturam pipeline/build compromise em escala."
   ],
   "cwes":["CWE-829","CWE-494","CWE-502"],"cases":[("SolarWinds SUNBURST, 2020","18k+ orgs","Update assinado"),("3CX, 2023","Desktop app","Supply chain"),("event-stream npm, 2018","Bitcoin wallet steal","Typosquatting"),("XZ Utils, 2024","SSH backdoor","Maintainer compromise")],
   "juice":["npm_audit","file_yaml_rce"],"det":["OSV-Scanner / Dependency-Track no CI","Verificação de hash de releases","Monitoramento de typosquatting","Audit de pipeline permissions"],
   "test":["WSTG-CONF-04: Review old backup files","Dependency composition analysis","Verify package lock integrity"],
   "asvs":["V14.2.1 Dependency inventory","V1.14 Build pipeline security"],
   "prev":["SBOM CycloneDX em cada release","Sigstore para assinatura de artefatos","Renovate com auto-merge só se CVE=0","Branch protection + OIDC no CI"],
   "refs":[("OWASP A03:2025","https://owasp.org/Top10/2025/A03_2025-Software_Supply_Chain_Failures/"),("SLSA","https://slsa.dev/"),("NTIA SBOM","https://www.ntia.gov/SBOM"),("CISA KEV","https://www.cisa.gov/known-exploited-vulnerabilities-catalog")],
   "diff":"Nova categoria — separa componente vulnerável de falha sistêmica de supply chain."},
  {"id":"A04","pt":"Falhas Criptográficas","en":"Cryptographic Failures",
   "p":[
     "Dados sensíveis sem proteção em trânsito ou repouso: TLS 1.0, MD5 para senhas, JWT sem validação de algoritmo. IBM Cost of a Data Breach 2024: US$ 4,88M de custo médio global.",
     "lib/insecurity.ts do Juice Shop usa MD5 para hash de senha — violação direta do ASVS. Localize a função hash() e proponha Argon2id.",
     "Criptografia mal aplicada é pior que ausência: transmite falsa sensação de segurança em auditorias superficiais.",
     "OWASP 2025: caiu de #2 para #4 — 3,80% das apps com uma das 32 CWEs de falha criptográfica. Frequentemente resulta em exposição de dados sensíveis ou comprometimento total do sistema."
   ],
   "cwes":["CWE-327","CWE-328","CWE-798","CWE-311"],"cases":[("Equifax, 2017","147M registros","TLS + patch"),("RockYou2024","10B senhas","Agregado leak"),("First American, 2019","885M docs","Sem auth em portal"),("Uber, 2016","57M usuários","AWS keys em Git")],
   "juice":["insecurity_md5","insecurity_jwt","password_weak"],"det":["Testssl.sh / sslyze","Auditoria de algoritmos em código","Busca de secrets (gitleaks, trufflehog)","Validação JWT (alg, exp, iss)"],
   "test":["WSTG-CRYP-01: Weak transport","WSTG-CRYP-03: Sensitive data exposure","WSTG-ATHN-10: Weak password policy"],
   "asvs":["V2.4 Credential storage","V6.2 Algorithms","V3.5 Token validation"],
   "prev":["TLS 1.3 only + HSTS preload","Argon2id cost factor calibrado","KMS com rotação automática","Nunca logar tokens ou PII em claro"],
   "refs":[("OWASP A04:2025","https://owasp.org/Top10/2025/A04_2025-Cryptographic_Failures/"),("NIST SP 800-57","https://csrc.nist.gov/publications/detail/sp/800-57-part-1/rev-5/final"),("JWT Best Practices","https://datatracker.ietf.org/doc/html/rfc8725")],
   "diff":"Era A02:2021 — reposicionada após misconfiguration subir."},
  {"id":"A05","pt":"Injeção","en":"Injection",
   "p":[
     "CWE-79 (XSS) lidera o TOP 25 MITRE 2025 com score 60,38 — mais que o dobro do segundo colocado. SQLi permanece em routes/login.ts e routes/search.ts do Juice Shop com concatenação direta.",
     "Injeção não se limita a SQL: LDAP, OS command, template e header injection compartilham a mesma raiz — dados não confiáveis interpretados como comando.",
     "Prepared statements e context-aware encoding resolvem a maioria dos casos; o gap está em ORMs mal usados e em microsserviços que montam queries dinâmicas.",
     "OWASP 2025: desceu de #3 para #5, mas permanece uma das categorias mais testadas — 38 CWEs e o maior volume de CVEs associadas. Espectro de XSS (alta frequência/baixo impacto unitário) a SQLi (baixa frequência/alto impacto)."
   ],
   "cwes":["CWE-79","CWE-89","CWE-78","CWE-94","CWE-77","CWE-20"],
   "cases":[("MOVEit SQLi, 2023","2.500+ orgs","Cl0p"),("British Airways, 2018","380k cartões","Magecart XSS"),("Sony PSN SQLi, 2011","77M contas","Sem parametrização"),("HBGary SQLi, 2011","WikiLeaks dispute","Union-based")],
   "juice":["login_sql","search_sqli","feedback_xss","profile_dom","error_stack"],"det":["SAST para fluxos source→sink","DAST com payloads OWASP","IAST em staging","WAF como camada compensatória"],
   "test":["WSTG-INPV-01: Reflected XSS","WSTG-INPV-02: Stored XSS","WSTG-INPV-05: SQL injection","WSTG-INPV-12: Command injection"],
   "asvs":["V5.1 Input validation","V5.3 Output encoding","V13.2 REST injection"],
   "prev":["ORM/param queries exclusivamente","CSP + HttpOnly cookies","Escape por contexto (HTML/JS/URL)","Princípio de least privilege no DB user"],
   "refs":[("OWASP A05:2025","https://owasp.org/Top10/2025/A05_2025-Injection/"),("SQLi Prevention","https://cheatsheetseries.owasp.org/cheatsheets/SQL_Injection_Prevention_Cheat_Sheet.html"),("XSS Prevention","https://cheatsheetseries.owasp.org/cheatsheets/Cross_Site_Scripting_Prevention_Cheat_Sheet.html")],
   "diff":"Desceu de A03:2021 mas CWE-79 no topo MITRE prova que o problema persiste."},
  {"id":"A06","pt":"Design Inseguro","en":"Insecure Design",
   "p":[
     "Falhas arquiteturais: sem rate limit, recuperação de senha previsível, lógica de cupom explorável. Corrigir em produção custa até 100× mais que no design (NIST SSDF).",
     "Threat modeling com STRIDE ou PASTA antes do sprint 1. Abuse user stories no backlog.",
     "Juice Shop: CAPTCHA só no client, cupons previsíveis, redirect allowlist por substring — todos defeitos de design, não de implementação pontual.",
     "OWASP 2025: caiu de #4 para #6 — a indústria avançou em threat modeling (NIST SSDF PW.1), mas abuse cases ainda escapam de scanners. PortSwigger: ~40% dos pentests encontram business logic flaws."
   ],
   "cwes":["CWE-352","CWE-770","CWE-840","CWE-20"],
   "cases":[("Twitter 2020","Contas verificadas","Admin tool design"),("Uber 2016","57M users","Hardcoded AWS creds"),("Robinhood CSRF, 2019","Trades não autorizados","Sem anti-CSRF")],
   "juice":["redirect_open","deluxe_coupon","csrf_transfer"],"det":["Review de abuse cases","Modelagem de ameaças documentada","Análise de lógica de negócio (BUA)","Rate limit metrics"],
   "test":["WSTG-BUSL-01: Business logic","WSTG-SESS-05: CSRF","WSTG-APIT-01: API business flow"],
   "asvs":["V1.1 Secure SDLC","V4.2 Anti-automation","V11.1 Business logic"],
   "prev":["Threat Dragon no repositório","Rate limit por IP+user","CSRF token em mutações","Limites de alocação (CWE-770)"],
   "refs":[("OWASP A06:2025","https://owasp.org/Top10/2025/A06_2025-Insecure_Design/"),("Threat Modeling","https://owasp.org/www-community/Threat_Modeling"),("NIST SSDF","https://csrc.nist.gov/Projects/ssdf")],
   "diff":"Mantido conceito de A04:2021 com ênfase em abuse cases."},
  {"id":"A07","pt":"Falhas de Autenticação","en":"Authentication Failures",
   "p":[
     "CWE-306 subiu 4 posições no TOP 25 2025. Credential stuffing representa 16% dos breaches no Verizon DBIR. MFA reduz risco em 99,2% segundo Microsoft — mas implementação fraca de JWT e session anula o ganho.",
     "Juice Shop: weak passwords hardcoded, bcrypt rounds=1, JWT com private key no repo — três falhas distintas em lib/insecurity.ts.",
     "Autenticação ≠ autorização. Esta categoria cobre identidade; A01 cobre o que o identificado pode fazer.",
     "OWASP 2025: mantém #7 com 36 CWEs. Frameworks padronizados (OAuth2/OIDC, Spring Security) reduzem ocorrências, mas MFA fraco e session management incorreto persistem — CWE-306 subiu 4 posições no MITRE TOP 25."
   ],
   "cwes":["CWE-306","CWE-287","CWE-384","CWE-521"],
   "cases":[("Okta support, 2023","Sessões de suporte","Credential leak"),("LastPass, 2022","Vault keys","Master password"),("Collection #1, 2019","773M emails","Stuffing"),("Cathay Pacific, 2018","9,4M passageiros","Senhas fracas")],
   "juice":["login_sql","insecurity_jwt","password_weak","admin_config"],"det":["Análise de política de senha","Teste de session fixation","JWT alg confusion test","MFA bypass attempts"],
   "test":["WSTG-ATHN-01: Credentials","WSTG-ATHN-03: Session management","WSTG-ATHN-09: Password reset"],
   "asvs":["V2.1 Password security","V3.2 Session management","V3.5 Token-based auth"],
   "prev":["MFA obrigatório (FIDO2/WebAuthn)","Bloqueio progressivo + CAPTCHA server-side","Rotação de session ID pós-login","Passwordless onde possível"],
   "refs":[("OWASP A07:2025","https://owasp.org/Top10/2025/A07_2025-Authentication_Failures/"),("ASVS","https://owasp.org/www-project-application-security-verification-standard/"),("NIST 800-63B","https://pages.nist.gov/800-63-4/")],
   "diff":"Mantido de A07:2021."},
  {"id":"A08","pt":"Falhas de Integridade","en":"Software or Data Integrity Failures",
   "p":[
     "Updates sem assinatura, CI/CD sem proteção, desserialização insegura. CWE-502 tem 11 entradas no CISA KEV. fileUpload.ts executa yaml.load dentro de vm.runInContext — vetor de negação de serviço e RCE.",
     "Integridade de dados entre microsserviços (mTLS, assinatura de mensagens) entra nesta categoria em arquiteturas distribuídas.",
     "Codecov (2021) provou que comprometer o pipeline equivale a comprometer todos os consumidores do artefato.",
     "OWASP 2025: mantém #8 — foco em integridade de software/dados em runtime, abaixo da cadeia de suprimentos (A03). 643 CWEs únicos mapeados a CVEs no NVD (vs 241 em 2021) ampliam a superfície de análise."
   ],
   "cwes":["CWE-502","CWE-345","CWE-829"],
   "cases":[("Codecov, 2021","CI script","Bash uploader"),("Confluence OGNL, 2022","RCE massivo","Deserialização"),("npm left-pad, 2016","Build quebrado","Dependência removida")],
   "juice":["file_yaml_rce","insecurity_jwt","mass_assignment"],"det":["Verificação de assinatura de update","Análise de desserialização","Pipeline permission audit","Subresource Integrity em CDN"],
   "test":["WSTG-INPV-11: Code injection","WSTG-CLNT-12: Subresource integrity"],
   "asvs":["V1.14 CI/CD security","V12.3 File integrity"],
   "prev":["Assinatura GPG/Sigstore em releases","Proibir desserialização de input externo","SRI em assets","mTLS service mesh"],
   "refs":[("OWASP A08:2025","https://owasp.org/Top10/2025/A08_2025-Software_or_Data_Integrity_Failures/"),("CWE-502","https://cwe.mitre.org/data/definitions/502.html")],
   "diff":"Mantido de A08:2021."},
  {"id":"A09","pt":"Falhas de Logging e Alerta","en":"Security Logging and Alerting Failures",
   "p":[
     "IBM 2024: automação de resposta reduz custo de breach em US$ 1,76M. Sem log correlacionado, MTTD mede meses — Marriott levou 4 anos.",
     "Juice Shop grava tokens em access.log acessível — dupla falha: logging inseguro (exposição) + ausência de alerta.",
     "LGPD Art. 46 e GDPR Art. 32 exigem capacidade de detectar incidentes — logging não é opcional em programas de segurança.",
     "OWASP 2025: mantém #9 — sub-representado em dados automatizados; promovido pela pesquisa comunitária. Nome atualizado para enfatizar alerting: log sem ação tem valor mínimo em resposta a incidentes (IBM: automação reduz ciclo em 108 dias)."
   ],
   "cwes":["CWE-778","CWE-117","CWE-532","CWE-200"],
   "cases":[("Target, 2013","40M cartões","Alertas ignorados"),("Marriott, 2018","500M registros","4 anos MTTD"),("SolarWinds, 2020","Detecção tardia","Log insuficiente")],
   "juice":["access_log_leak","error_stack"],"det":["SIEM rules para auth failures","UEBA em contas privilegiadas","Audit trail imutável","Tabletop com logs reais"],
   "test":["WSTG-LOGG-01: Log review","WSTG-LOGG-02: Log injection"],
   "asvs":["V7.1 Log content","V7.2 Log protection","V7.4 Alerting"],
   "prev":["JSON estruturado: who/what/when/outcome","Centralização em SIEM com retention","Alertas com runbook linkado","Redação de PII em logs"],
   "refs":[("OWASP A09:2025","https://owasp.org/Top10/2025/A09_2025-Security_Logging_and_Alerting_Failures/"),("NIST AU controls","https://csrc.nist.gov/Projects/risk-management/sp800-53-controls/release-search#!/control?version=5.1&number=AU")],
   "diff":"Logging and Alerting — ênfase em alertas acionáveis, não só em gravar."},
  {"id":"A10","pt":"Tratamento Incorreto de Exceções","en":"Mishandling of Exceptional Conditions",
   "p":[
     "Nova em 2025. Stack traces em HTTP 500, fail-open em falha de auth, race conditions e estados parciais após timeout. Equifax (Struts) e Heartbleed são casos de exceção mal tratada com impacto nacional.",
     "CWEs de memory corruption (787, 416, 125) dominam em código nativo — relevante para quem também desenvolve em C/C++ embarcado.",
     "Diferencie de A02: aqui o código executa, mas o caminho de erro vaza informação ou deixa o sistema em estado inseguro.",
     "OWASP 2025: categoria nova com 24 CWEs — error handling, fail-open, race conditions e estados inconsistentes após exceções. Substitui SSRF no Top 10 (SSRF permanece em A01/CWE-918 #22 MITRE). CISA KEV: 12 CVEs ativos em CWE-787, 14 em CWE-416."
   ],
   "cwes":["CWE-209","CWE-787","CWE-416","CWE-125","CWE-476","CWE-400"],
   "cases":[("Equifax Struts, 2017","147M","Exception→RCE"),("Heartbleed, 2014","OOB read","OpenSSL"),("Cloudflare, 2017","Memory leak","Parser bug")],
   "juice":["search_sqli","error_stack"],"det":["Fuzzing de error paths","Verificar respostas 500 em produção","Static analysis memory safety","Crash reporting sem PII"],
   "test":["WSTG-ERRH-01: Error codes","WSTG-ERRH-02: Stack traces"],
   "asvs":["V7.4 Error handling","V14.5 Unhandled exceptions"],
   "prev":["Mensagem genérica ao cliente","Fail-closed em authZ","Circuit breaker + timeout","Rust/ASAN em código nativo"],
   "refs":[("OWASP A10:2025","https://owasp.org/Top10/2025/A10_2025-Mishandling_of_Exceptional_Conditions/"),("CWE-787","https://cwe.mitre.org/data/definitions/787.html")],
   "diff":"Nova — substitui SSRF no Top 10 (SSRF continua em CWE-918 #22)."},
]

CWE_LIST = [
  (1,"CWE-79","Cross-site Scripting (XSS)","Injeção de script no contexto HTML do browser. DOM, reflected, stored.","A05",None,60.38,7),
  (2,"CWE-89","SQL Injection","Query SQL montada por concatenação.","A05","login_sql",28.72,4),
  (3,"CWE-352","Cross-Site Request Forgery","Browser autenticado executa ação forjada.","A06",None,13.64,0),
  (4,"CWE-862","Missing Authorization","Recurso acessado sem checagem de permissão.","A01","basket_idor",13.28,0),
  (5,"CWE-787","Out-of-bounds Write","Escrita além do buffer — memory corruption.","A10",None,12.68,12),
  (6,"CWE-22","Path Traversal","../ em paths de arquivo.","A01",None,8.99,10),
  (7,"CWE-416","Use After Free","Ponteiro após liberação.","A10",None,8.47,14),
  (8,"CWE-125","Out-of-bounds Read","Leitura além dos limites — info leak.","A10",None,7.88,3),
  (9,"CWE-78","OS Command Injection","Input vira comando de SO.","A05",None,7.85,20),
  (10,"CWE-94","Code Injection","Geração dinâmica de código executável.","A05",None,7.57,7),
  (11,"CWE-120","Classic Buffer Overflow","Cópia sem checagem de tamanho.","A10",None,6.96,0),
  (12,"CWE-434","Unrestricted Upload","Upload de tipo perigoso sem validação.","A01","file_yaml_rce",6.87,4),
  (13,"CWE-476","NULL Pointer Dereference","Crash ou exploit via NULL.","A10",None,6.41,0),
  (14,"CWE-121","Stack Buffer Overflow","Overflow na pilha.","A10",None,5.75,4),
  (15,"CWE-502","Deserialization","Objeto de fonte não confiável.","A08","file_yaml_rce",5.23,11),
  (16,"CWE-122","Heap Buffer Overflow","Overflow no heap.","A10",None,5.21,6),
  (17,"CWE-863","Incorrect Authorization","Lógica de autorização errada.","A01","basket_idor",4.14,4),
  (18,"CWE-20","Improper Input Validation","Entrada não validada adequadamente.","A05","login_sql",4.09,2),
  (19,"CWE-284","Improper Access Control","Política de acesso ausente.","A01","basket_idor",4.07,1),
  (20,"CWE-200","Information Exposure","Dados sensíveis para ator não autorizado.","A02","insecurity_md5",4.01,1),
  (21,"CWE-306","Missing Authentication","Função crítica sem login.","A07",None,3.47,11),
  (22,"CWE-918","SSRF","Request server-side para URL atacante.","A01",None,3.36,0),
  (23,"CWE-77","Command Injection","Injeção em interpreter de comandos.","A05",None,3.15,2),
  (24,"CWE-639","Auth Bypass via User Key","ID controlado pelo usuário sem validação.","A01","basket_idor",2.62,0),
  (25,"CWE-770","Resource Allocation w/o Limits","Sem throttling — DoS, brute force.","A06",None,2.54,0),
]

QUIZ = [
  ("Qual categoria OWASP 2025 permanece #1?","A01 Broken Access Control","A05 Injection","A04 Crypto",0),
  ("CWE com maior score MITRE 2025?","CWE-89 SQLi","CWE-79 XSS","CWE-862",1),
  ("Arquivo Juice Shop com SQLi no login?","routes/basket.ts","routes/login.ts","routes/profile.ts",1),
  ("CWE mapeada ao challenge View Basket?","CWE-639","CWE-79","CWE-502",0),
  ("Nova categoria OWASP 2025?","A03 Supply Chain","A06 Insecure Design","A09 Logging",0),
  ("Função hash insegura em insecurity.ts?","SHA-256","MD5","bcrypt rounds=12",1),
  ("CWE-502 relaciona-se a qual OWASP?","A08 Integrity","A02 Misconfig","A10 Exceptions",0),
  ("O que saiu do Top 10:2025 em relação a 2021?","Injection","SSRF","Crypto Failures",1),
  ("Payload clássico SQLi no Juice Shop?","[tag script] alert(1)","' OR 1=1--","../../../etc/passwd",1),
  ("Verificação JWT deve fixar?","algorithms allowlist","expiresIn only","issuer optional",0),
]

MARKET = [
  ("US$ 4,88M","Custo médio breach","IBM Cost of Data Breach 2024","https://www.ibm.com/reports/data-breach"),
  ("US$ 1,76M","Economia com automação IR","IBM Cost of Data Breach 2024","https://www.ibm.com/reports/data-breach"),
  ("277 dias","MTTI médio global","IBM Cost of Data Breach 2024","https://www.ibm.com/reports/data-breach"),
  ("60,38","Score CWE-79","MITRE CWE TOP 25 2025","https://cwe.mitre.org/top25/archive/2025/2025_key_insights.html"),
  ("16%","Breaches via credential stuffing","Verizon DBIR 2024","https://www.verizon.com/business/resources/reports/dbir/"),
  ("15%","Incidentes web — misconfig","Verizon DBIR 2024","https://www.verizon.com/business/resources/reports/dbir/"),
  ("11","CVEs KEV em CWE-502","CISA KEV Catalog","https://www.cisa.gov/known-exploited-vulnerabilities-catalog"),
  ("+5","Posições CWE-862 vs 2024","MITRE CWE TOP 25 2025","https://cwe.mitre.org/top25/archive/2025/2025_key_insights.html"),
]