# 10 simuladores Juice Shop — 1 por categoria OWASP Top 10:2025

SIMULATORS = [
  {
    "kind": "a01", "owasp": "A01", "cwe": "CWE-639",
    "title": "routes/basket.ts · IDOR / BOLA",
    "ide_file": "routes/basket.ts",
    "input_id": "sim-a01", "input_type": "number", "input_value": "2", "input_aria": "basket id",
    "run_label": "Executar",
    "presets": [("ID alheio", "2")],
  },
  {
    "kind": "a02", "owasp": "A02", "cwe": "CWE-16",
    "title": "routes/appConfiguration.ts · Admin sem auth",
    "ide_file": "routes/appConfiguration.ts",
    "input_id": "sim-a02", "input_type": "text", "input_value": "/rest/admin/application-configuration", "input_aria": "endpoint",
    "run_label": "Executar",
    "presets": [("Config admin", "/rest/admin/application-configuration")],
  },
  {
    "kind": "a03", "owasp": "A03", "cwe": "CWE-829",
    "title": "package.json · Dependência vulnerável",
    "ide_file": "package.json",
    "input_id": "sim-a03", "input_type": "text", "input_value": "jsonwebtoken@0.4.0", "input_aria": "pacote",
    "run_label": "Executar",
    "presets": [("JWT antigo", "jsonwebtoken@0.4.0"), ("sanitize-html", "sanitize-html@1.4.2")],
  },
  {
    "kind": "a04", "owasp": "A04", "cwe": "CWE-327",
    "title": "lib/insecurity.ts · MD5 em senhas",
    "ide_file": "lib/insecurity.ts",
    "input_id": "sim-a04", "input_type": "text", "input_value": "P@ssw0rd!", "input_aria": "senha",
    "run_label": "Executar",
    "presets": [("Senha comum", "admin123")],
  },
  {
    "kind": "a05", "owasp": "A05", "cwe": "CWE-89",
    "title": "routes/login.ts · SQL Injection",
    "ide_file": "routes/login.ts",
    "input_id": "sim-a05", "input_type": "text", "input_value": "' OR 1=1--", "input_aria": "email",
    "run_label": "Executar",
    "presets": [("Payload clássico", "' OR 1=1--")],
  },
  {
    "kind": "a06", "owasp": "A06", "cwe": "CWE-352",
    "title": "routes/wallet.ts · CSRF em transferência",
    "ide_file": "routes/wallet.ts",
    "input_id": "sim-a06", "input_type": "number", "input_value": "999", "input_aria": "valor transferência",
    "run_label": "Executar",
    "presets": [("PoC CSRF", "999")],
  },
  {
    "kind": "a07", "owasp": "A07", "cwe": "CWE-521",
    "title": "lib/insecurity.ts · Política de senha fraca",
    "ide_file": "lib/insecurity.ts",
    "input_id": "sim-a07", "input_type": "text", "input_value": "a", "input_aria": "senha registro",
    "run_label": "Executar",
    "presets": [("1 caractere", "a"), ("rockyou", "123456")],
  },
  {
    "kind": "a08", "owasp": "A08", "cwe": "CWE-502",
    "title": "routes/fileUpload.ts · Deserialização YAML",
    "ide_file": "routes/fileUpload.ts",
    "input_id": "sim-a08", "input_type": "text",
    "input_value": "!!js/function >{ return process.env }",
    "input_aria": "payload yaml",
    "run_label": "Executar",
    "presets": [("YAML perigoso", "!!js/function >{ return process.env }")],
  },
  {
    "kind": "a09", "owasp": "A09", "cwe": "CWE-200",
    "title": "routes/accessLog.ts · Logs expõem JWT",
    "ide_file": "routes/accessLog.ts",
    "input_id": "sim-a09", "input_type": "text", "input_value": "/support/logs", "input_aria": "path logs",
    "run_label": "Executar",
    "presets": [("Access log", "/support/logs")],
  },
  {
    "kind": "a10", "owasp": "A10", "cwe": "CWE-209",
    "title": "routes/search.ts · Stack trace verboso",
    "ide_file": "routes/search.ts",
    "input_id": "sim-a10", "input_type": "text", "input_value": "'", "input_aria": "busca",
    "run_label": "Executar",
    "presets": [("Syntax error", "'"), ("UNION probe", "')) UNION SELECT 1--")],
  },
]